'use strict';
// ════════════════════════════════════════════════════════
//  DATA — ADEXI, SPQ-35 and Monotropism Questionnaire
//  Rendered by likert.js; each entry in LIKERT_TESTS drives one screen
// ════════════════════════════════════════════════════════

// ADEXI: Holst Y, Thorell LB (2018). Int J Methods Psychiatr Res 27(1):e1567.
// Italian self-report from www.chexi.se (translator F. Denoth, IFC-CNR); free to use, no permission needed.
// Two typos of the Italian PDF corrected (items 4 and 11).
const ADEXI_Q = {
  it: [
    "Faccio fatica a ricordare istruzioni lunghe",
    "Fatico a ricordare cosa sto facendo quando mi trovo nel mezzo di un'attività",
    "Ho la tendenza a intraprendere azioni senza prima pensare alle possibili conseguenze",
    "Ho difficoltà a trattenermi dal fare una cosa che mi piace anche se so che non è permesso farla",
    "Quando mi si chiede di svolgere una serie di azioni, ricordo solo la prima e l'ultima",
    "Ho difficoltà a smettere di sorridere o ridere in situazioni in cui questo atteggiamento è inappropriato",
    "Ho difficoltà a trovare un modo diverso di risolvere un problema quando ormai ho già in mente un modo per risolverlo (anche se mi rendo conto che non funziona)",
    "Dimentico facilmente ciò che mi è stato chiesto di andare a prendere",
    "Ho difficoltà a pianificare un'attività (es. ricordare di portare tutto il necessario quando parto per un viaggio o quando vado a lavoro o a scuola)",
    "Ho difficoltà a smettere di fare una cosa che mi piace (es. guardare la TV, stare in Internet, fare videogiochi la sera anche quando mi rendo conto che è tardi)",
    "Ho difficoltà a comprendere le spiegazioni/istruzioni verbali per fare qualcosa a meno che al contempo mi si mostri in pratica come farla",
    "Ho difficoltà a svolgere attività che richiedono diversi passaggi",
    "Ho difficoltà a programmare a lungo termine/periodo o imparare dall'esperienza",
    "Le persone che incontro sembrano pensare che io sia più agitato/incontrollato (fuori dagli schemi) rispetto ad altre persone della mia stessa età",
  ],
  en: [
    "I have difficulty remembering lengthy instructions",
    "I have difficulty remembering what I am doing in the middle of an activity",
    "I have a tendency to do things without first thinking about what could happen",
    "I have difficulty stopping myself from doing something that I like even though someone tells me that it is not allowed.",
    "When someone asks me to do several things, I remember only the first or last",
    "I have difficulty refraining for smiling or laughing in situations where it is inappropriate",
    "I have difficulty coming up with a different way of solving a problem when I get stuck",
    "When someone asks me to fetch something, I forget what I am supposed to fetch",
    "I have difficulty planning for an activity (e.g., remembering to bring everything necessary when going on a trip/to work/to school)",
    "I have difficulty stopping an activity that I like (e.g., I watch TV or sit in front of the computer in the evening even though it is time to go to bed)",
    "I have difficulty understanding verbal instructions unless I am also shown how to do something",
    "I have difficulties with tasks or activities that involve several steps",
    "I have difficulty thinking ahead or learning from experience",
    "People that I meet seem to think that I am more lively/wilder compared to other people my age",
  ],
};
const ADEXI_OPTS = {
  it: ["Completamente in disaccordo", "In disaccordo", "Parzialmente d'accordo", "D'accordo", "Completamente d'accordo"],
  en: ["Definitely not true", "Not true", "Partially true", "True", "Definitely true"],
};
// 0-based item indices, from the official ADEXI subscales sheet
const ADEXI_WM  = [0, 1, 4, 6, 7, 8, 10, 11, 12];
const ADEXI_INH = [2, 3, 5, 9, 13];

// SPQ-35: Tavassoli T, Hoekstra RA, Baron-Cohen S (2014). Mol Autism 5:29. (c) ARC, University of Cambridge.
// Italian version by R. Keller and S. Brighenti (Torino), distributed by the ARC.
// Items are stored in English order. The Italian sheet moves English item 35 to position 27 and
// words it negatively, so that item is reverse scored in Italian only.
const SPQ_Q = {
  it: [
    "Sarei capace di distinguere le diverse persone dal loro odore.",
    "Sarei capace di identificare se una fragola è matura solo dall'odore.",
    "Sarei capace di identificare visivamente il cambiamento di luminosità di una luce ogni volta che l'interruttore viene spostato di poco (una tacca).",
    "Mi accorgerei se qualcuno aggiungesse 5 gocce di succo di limone al mio bicchiere d'acqua.",
    "Sarei capace di sentire una foglia muoversi se sospinta dal vento in una strada tranquilla.",
    "Sarei capace di distinguere la differenza di gusto tra due marche di patatine salate.",
    "Anche se ci pensassi, non riuscirei a sentire l'etichetta sul retro della mia maglia.",
    "Riesco a sentire l'elettricità ronzare nei muri.",
    "Noto lo sfarfallio del computer anche quando funziona correttamente.",
    "Sarei capace di notare un minimo cambiamento (ad es. di un grado) di temperatura nell'ambiente esterno.",
    "Sarei capace di sentire un taglio di un millimetro sulla mia pelle.",
    "Sarei capace di distinguere la differenza di peso tra due monete di dimensioni diverse poste sul palmo della mia mano ad occhi chiusi.",
    "Non potrei distinguere una persona conosciuta da una estranea dal loro odore.",
    "Non potrei identificare se il pane è raffermo solamente dall'odore.",
    "Sarei capace di identificare il suono di un aspirapolvere da qualsiasi stanza in un palazzo di due piani.",
    "Sarei capace di sentire l'elastico che tiene su le calze se mi soffermassi a pensarci.",
    "Sarei capace di percepire le differenze di gusto tra due caramelle apparentemente identiche.",
    "Noto il peso e la pressione di un cappello sulla mia testa.",
    "Riuscirei a sentire se un singolo capello toccasse il dorso della mia mano.",
    "Passeggiando, sarei capace di sentire le vibrazioni di un camion che passa, anche ad occhi chiusi.",
    "Sarei capace di sentire la più piccola perdita di gas da qualsiasi punto della casa.",
    "Non noterei se qualcuno cambiasse il suo profumo solamente dall'odore.",
    "Non posso uscire senza occhiali da sole se la luce del sole è forte.",
    "Riuscirei a sentire il cambiamento nella temperatura di una tazzina di caffè che è stata messa da parte per 1 minuto.",
    "Sarei il primo a sentire se ci fosse una mosca nella stanza.",
    "Guardando una pila di maglie blu che dovrebbero essere identiche esposte in un negozio, riesco a notarne le differenze.",
    "Riuscirei a sentire la differenza di odore tra la maggior parte degli uomini e delle donne.",
    "Sarei capace di sentire le singole note anche in accordi con 10 note.",
    "Chiudo le tende per evitare la luce forte.",
    "Sarei capace di distinguere due marche di caffè solamente dal loro odore, anche ad occhi chiusi.",
    "Riesco a vedere le particelle di polvere nell'aria nella maggior parte degli ambienti.",
    "Non riuscirei a sentire la differenza tra due marche di salsa di pomodoro se contenessero una concentrazione di sale diversa.",
    "Sarei capace di sentire il minimo odore di bruciato da qualsiasi punto della casa.",
    "Se il mio cellulare mi stesse vibrando in tasca, me ne accorgerei velocemente.",
    "Non identificherei subito un nuovo odore in casa prima degli altri.",
  ],
  en: [
    "I can recognize different people by the way they smell.",
    "I would be able to tell if a strawberry was ripe just by smelling it.",
    "I would notice right away that it got brighter if a dimmer control switch moved up one notch.",
    "I would notice right away if someone added 5 drops of lemon juice to my cup of water.",
    "I would be able to hear the sound of a leaf blown by the wind on a quiet street.",
    "I would be able to taste the difference between two brands of salty potato chips/crisps.",
    "I would not be able to feel the label at the back of my shirt even if I thought about it.",
    "I can hear electricity humming in the walls.",
    "I notice the flickering of a desktop computer even when it is working properly.",
    "I would be able to notice a small change (e.g. 1 degree) in the temperature of the weather.",
    "I would be able to feel a small (e.g. one millimetre) paper cut in my skin.",
    "I would be able to tell the weight difference between two different coin sizes on the palm of my hand with my eyes closed.",
    "I could not distinguish a familiar person and a stranger by their smell.",
    "I could not tell if bread was stale purely by its smell.",
    "I would be able to hear the sound of a vacuum cleaner from any room in a two-storey building.",
    "I would be able to feel the elastic holding up my socks if I stop and thought about it.",
    "I would be able to taste the difference between apparently identical pieces of candy.",
    "I notice the weight and pressure of a hat on my head.",
    "I would feel if a single hair touched the back of my hand.",
    "If I was walking along, I would be able to feel a passing truck's vibrations even if my eyes were closed.",
    "I would be able to smell the smallest gas leak from anywhere in the house.",
    "I wouldn't notice if someone changed their perfume, by smell alone.",
    "I can't go out in bright sunlight without sunglasses.",
    "I would be able to feel a change in the temperature of a cup of coffee after it had sat for 1 minute.",
    "I would be the first to hear if there was a fly in the room.",
    "If I look at a pile of blue sweaters in a shop that are meant to be identical, I would be able to see differences between them.",
    "I would be able to smell the difference between most men and women.",
    "I would be able to hear each note in a chord even if there were 10 notes.",
    "I close curtains to avoid bright lights.",
    "I would be able to distinguish two brands of coffee by their smell, even with my eyes closed.",
    "I can see dust particles in the air in most environments.",
    "I wouldn't be able to taste the difference between two brands of tomato sauce if they had different concentrations of salt.",
    "I would be able to smell the smallest amount of burning from anywhere in the house.",
    "If my mobile phone was vibrating in my pocket I would be quick to sense it.",
    "I would detect a new smell in my house instantly before anyone else.",
  ],
};
const SPQ_OPTS = {
  it: ["Fortemente d'accordo", "D'accordo", "Disaccordo", "Fortemente in disaccordo"],
  en: ["Strongly agree", "Agree", "Disagree", "Strongly disagree"],
};
// ARC scoring sheet: 0 = strongly agree ... 3 = strongly disagree; items 7, 13, 14, 22, 32 reversed
const SPQ_REVERSED   = [6, 12, 13, 21, 31];
const SPQ_IT_NEGATED = 34;
const SPQ_MAX = 105;

// Monotropism Questionnaire: Garau V, Woods R, Chown N, Hallett S, Murray F, Wood R, Murray A (2023), OSF.
// Licence CC BY-NC-SA 4.0. No validated Italian version exists: the Italian wording is a NeuroScreen
// translation released under the same licence.
const MQ_Q = {
  it: [
    "Dopo un periodo di instabilità ho bisogno di un ambiente tranquillo e prevedibile.",
    "Ho bisogno di un ambiente tranquillo e prevedibile per passare facilmente da un'attività all'altra.",
    "Spesso faccio fatica a concentrarmi in ambienti affollati e/o imprevedibili.",
    "Le interruzioni improvvise e inaspettate della mia attenzione mi fanno sobbalzare.",
    "Mi angoscia essere distolto/a all'improvviso da qualcosa in cui sono immerso/a.",
    "Raramente trovo scomodo mantenere il contatto visivo e allo stesso tempo conversare con un'altra persona.",
    "Noto spesso dettagli che gli altri non notano.",
    "Dedicarmi a un'attività che mi interessa spesso riduce la mia ansia.",
    "Le interazioni sociali mi risultano più comode se si parla di un argomento che mi interessa.",
    "Spesso sono così concentrato/a sulle attività che mi appassionano da non accorgermi di ciò che succede intorno.",
    "Posso diventare piuttosto bravo/a in qualcosa anche se non mi interessa particolarmente.",
    "Spesso perdo la cognizione del tempo quando mi dedico alle attività che mi appassionano.",
    "A volte evito di parlare perché non riesco a prevedere con sicurezza come reagiranno gli altri, soprattutto gli sconosciuti.",
    "Tendo a fare le cose perché le trovo interessanti, più che per le aspettative della società.",
    "Raramente trovo caotiche le situazioni sociali.",
    "Non mi dà fastidio se qualcuno mi interrompe mentre sto facendo qualcosa.",
    "Quando lavoro a qualcosa sono aperto/a a suggerimenti utili.",
    "Spesso faccio fatica a cambiare argomento dopo essermi dedicato/a a lungo a un'attività.",
    "Spesso mi dedico alle attività che mi appassionano per sfuggire all'ansia.",
    "Le routine sono un'importante fonte di stabilità e sicurezza.",
    "Gestisco l'incertezza creando delle routine.",
    "Provo spesso ansia per questioni su cui ho poca certezza.",
    "Faccio fatica a impegnarmi in un compito che non mi interessa, anche se è importante.",
    "Trovo spesso rilassante fare stimming (per esempio giocherellare con le mani o dondolarmi).",
    "In ogni periodo della mia vita di solito ho pochi argomenti che mi appassionano.",
    "Faccio fatica a filtrare i suoni quando non sto facendo qualcosa su cui sono concentrato/a.",
    "Di solito intendo esattamente quello che dico, niente di più.",
    "Mi capita spesso di fare lunghe discussioni su argomenti che trovo interessanti, anche se chi parla con me non li trova tali.",
    "A volte, quando sono concentrato/a su un compito, dico per sbaglio qualcosa che gli altri trovano offensivo o scortese.",
    "A volte posso essere molto turbato/a da un argomento che gli altri considerano banale.",
    "Mi è facile seguire le discussioni di gruppo in cui parlano tutti.",
    "Spesso, quando sono concentrato/a su un'attività, non mi accorgo di avere sete o fame.",
    "Spesso, quando sono concentrato/a su un'attività, non mi accorgo di dover andare in bagno.",
    "Quando ci sono molte informazioni da considerare, spesso faccio fatica a prendere una decisione.",
    "A volte prendere una decisione è così difficile che resto fisicamente bloccato/a.",
    "A volte resto concentrato/a su un episodio per molto tempo (giorni) dopo che è successo.",
    "A volte divento molto ansioso/a pensando alle tante situazioni che potrebbero verificarsi in un evento futuro.",
    "A volte, quando sono concentrato/a su un'attività, non ricordo tutte le informazioni che mi servirebbero per prendere buone decisioni.",
    "Le persone mi dicono che mi fisso sulle cose.",
    "Un problema che non riesco a risolvere mi angoscia e/o faccio fatica a metterlo da parte.",
    "Tendo a sentirmi impacciato/a e sotto osservazione, a meno che non sia profondamente assorbito/a in un compito.",
    "Spesso resto bloccato/a a pensare a tutte le possibili conseguenze di una decisione.",
    "Quando qualcosa mi interessa, tendo ad appassionarmene.",
    "Quando un argomento mi interessa, mi piace imparare tutto ciò che posso su di esso.",
    "Sono ancora affascinato/a da molte delle cose che mi interessavano quando ero molto più giovane.",
    "Raramente mi ritrovo bloccato/a in circoli di pensieri.",
    "Ritorno spesso su pensieri precedenti.",
  ],
  en: [
    "After a period of instability, I need a quiet and predictable environment.",
    "I need a quiet and predictable environment for me to switch from one task to another easily.",
    "I often struggle to concentrate in busy and/or unpredictable environments.",
    "I find sudden unexpected disruptions to my attention startling.",
    "It's distressing to be unexpectedly pulled away from something I'm engaged in.",
    "I rarely find simultaneously holding eye contact and making a verbal conversation with another person uncomfortable.",
    "I often notice details that others do not.",
    "Involvement in an activity of interest often reduces my anxiety level.",
    "I find social interactions more comfortable if communicating about a topic of interest to me.",
    "I am often totally focused on activities I am passionate about, to the point I am unaware of other events.",
    "I can get quite good at something even if I'm not especially interested in it.",
    "I often lose sense of time when engaging in activities I am passionate about.",
    "I sometimes avoid talking because I cannot reliably predict how others will react, especially strangers.",
    "I tend to do activities because I find them interesting, instead of due to societal expectations.",
    "I rarely find social situations chaotic.",
    "I don't mind if someone interrupts me when I'm in the middle of an activity.",
    "When I'm working on something, I'm open to helpful suggestions.",
    "I often find it difficult to switch topics after engaging in an activity for a long time.",
    "I often engage in activities I am passionate about to escape from anxiety.",
    "Routines provide an important source of stability and safety.",
    "I manage uncertainty by creating routines.",
    "I often experience anxiety over matters I have little certainty over.",
    "I find it difficult to engage in a task of no interest to me even if it is important.",
    "I often find engaging in stimming (e.g., fidgeting, rocking) to be relaxing.",
    "I am usually passionate about a few topics at any one time in my life.",
    "I have trouble filtering out sounds when I am not doing something I'm focused on.",
    "I usually mean what I say and no more than that.",
    "I often engage in lengthy discussions on topics I find interesting even though my conversational partner(s) do not.",
    "I sometimes accidentally say something others find offensive/rude when I am focused on a task.",
    "I can sometimes be very distressed by a topic that others think of as trivial.",
    "I find it easy to keep up with group discussions where everyone is speaking.",
    "Often when I am focused on activities, I do not notice I am thirsty or hungry.",
    "Often when I am focused on activities, I do not notice I need the bathroom.",
    "When there is a lot of information to consider, I often struggle to make a decision.",
    "Sometimes making a decision is so hard I get physically stuck.",
    "I sometimes focus on an incident for a substantial time (days) after the event.",
    "I sometimes become highly anxious by focusing on the many possible situations that might occur at a future event.",
    "Sometimes when I am focused on an activity, I do not recall all the information I might need to make good decisions.",
    "People tell me I get fixated on things.",
    "I find a problem I can't solve distressing and/or hard to put down.",
    "I tend to feel quite self-conscious unless I'm deeply absorbed in a task.",
    "I often get stuck thinking about all the possibilities that might come out of a decision.",
    "When I am interested in something, I tend to be passionate about it.",
    "When I am interested in a topic, I like to learn everything I can about that topic.",
    "I am still fascinated by many of the things I was interested in when I was much younger.",
    "I rarely find myself getting stuck in loops of thought.",
    "I often loop back to previous thoughts.",
  ],
};
const MQ_OPTS = {
  it: ["Fortemente in disaccordo", "In disaccordo", "Né d'accordo né in disaccordo", "D'accordo", "Fortemente d'accordo", "Non applicabile"],
  en: ["Strongly disagree", "Disagree", "Neither agree nor disagree", "Agree", "Strongly agree", "Not applicable"],
};
const MQ_REVERSED = [5, 10, 14, 15, 16, 30, 45];

// Stored answer = option index + 1, except MQ "Not applicable" stored as 0 (excluded from the mean)
const LIKERT_TESTS = {
  adexi: { items: ADEXI_Q, opts: ADEXI_OPTS, badge: 'ADEXI', badgeCls: 'badge-teal', instrKey: 'adexiInstr' },
  spq:   { items: SPQ_Q,   opts: SPQ_OPTS,   badge: 'SPQ-35', badgeCls: 'badge-warn', instrKey: 'spqInstr' },
  mq:    { items: MQ_Q,    opts: MQ_OPTS,    badge: 'MQ', badgeCls: 'badge-purple', instrKey: 'mqInstr', naLast: true },
};
