'use strict';
// ════════════════════════════════════════════════════════
//  UI TRANSLATIONS — all display strings for IT and EN
// ════════════════════════════════════════════════════════

const UI = {
  it: {
    // Nav steps
    stepWelcome: '1 · Benvenuto', stepAq10: '2 · AQ-10', stepAsrs: '3 · ASRS',
    stepRaads:   '4 · RAADS-14',  stepCatq:  '5 · CAT-Q',
    stepTasks:   '6 · Task',      stepWebcam: '7 · Webcam', stepResults: '8 · Risultati',
    // Welcome screen
    badgeWelcome:      'Screening neurosviluppo',
    appSubtitle:       'Screening non clinico per tratti autistici e ADHD negli adulti',
    disclaimerText:    '<strong>⚠️ Importante:</strong> Questo strumento <em>non è un test diagnostico</em>. I risultati sono indicativi e non sostituiscono la valutazione di uno specialista. Nessun dato viene inviato a server remoti — tutto rimane nel tuo browser.',
    ossNotice:         '<strong>Open source · Zero pubblicità · I tuoi dati restano nel browser</strong><br>La maggior parte dei test online ha imprecisioni e poi propone report a €20–80. NeuroScreen usa gli stessi strumenti validati scientificamente, completamente gratuiti, senza raccogliere alcun dato.',
    selectTests:       'Personalizza lo screening:',
    durationLabel:     (min) => `Durata stimata: <strong>~${min} min</strong>`,
    aq10Meta:          '10 domande · ~3 min · ASD',
    aq50Meta:          '50 domande · ~15 min · ASD',
    asrsMeta:          '6 domande · ~2 min · ADHD',
    asrs18Meta:        '18 domande · ~6 min · ADHD',
    extendedLabel:     'Modalità estesa',
    extendedDesc:      'AQ-50 (50 domande, ~15 min) e ASRS completo (18 domande, ~6 min). Stessi strumenti scientificamente validati, versioni più complete.',
    aqExtLabel:        'Estendi a AQ-50 · 50 domande · ~15 min',
    asrsExtLabel:      'Estendi ad ASRS-18 · 18 domande · ~6 min',
    raadsMeta:         '14 domande · ~5 min · ASD',
    catqMeta:          '25 domande · ~7 min · opzionale',
    cptMeta:           '60 secondi · test obiettivo',
    socialMeta:        '6 trial · ~3 min',
    webcamMeta:        '45 secondi · richiede HTTP',
    aq10Short:         'Autismo in 10 domande. Calibrato su dati di popolazione adulta. Soglia ≥6/10.',
    asrsShort:         'ADHD in 6 domande. Specificità 99.5% — quasi nessun falso positivo. Soglia ≥4/6.',
    raadsShort:        'Scala autismo più dettagliata: mentalizzazione, ansia sociale e reattività sensoriale. Soglia ≥14/42.',
    catqShort:         'Misura il camouflaging: quanto nascondi o compensi i tratti autistici quando sei con gli altri. Utile se gli altri test danno punteggi bassi ma ti riconosci nei tratti.',
    copyrightLine:     '© 2026 scozzadroid-cpu · codice con licenza <a href="https://github.com/scozzadroid-cpu/neuroscreen/blob/main/LICENSE" target="_blank" rel="noopener" class="ref-link">MIT</a> · i questionari appartengono ai rispettivi autori (<a href="https://github.com/scozzadroid-cpu/neuroscreen/blob/main/THIRD_PARTY_NOTICES.md" target="_blank" rel="noopener" class="ref-link">note</a>)',
    stampNote_aq10: 'Allison, Auyeung e Baron-Cohen (2012) hanno confrontato adulti con diagnosi di autismo e controlli. Con soglia ≥6 sensibilità 88% e specificità 91%. Limite: negli adulti inviati a una valutazione specialistica l\'accuratezza è molto più bassa (Ashwood 2016).',
    stampNote_aq50: 'Baron-Cohen et al. (2001) hanno confrontato adulti con sindrome di Asperger o autismo ad alto funzionamento e controlli, con soglia ≥32. Limite: come per l\'AQ-10, negli adulti inviati a valutazione specialistica predice male la diagnosi (Ashwood 2016).',
    stampNote_asrs: 'Kessler et al. (2005), per l\'OMS, hanno confrontato le risposte con interviste cliniche. Parte A: sensibilità 68,7%, specificità 99,5%. Limite: circa un adulto con ADHD su tre resta sotto soglia. La Parte B della versione estesa non ha una soglia validata.',
    stampNote_raads14: 'Eriksson et al. (2013), su adulti seguiti in ambito psichiatrico. Sensibilità 97%, ma specificità 46–64% rispetto ad ADHD e altri disturbi psichiatrici (circa 95% rispetto ai controlli). Limite: molti falsi positivi in chi ha altre condizioni psichiatriche.',
    stampNote_cati: 'English et al. (2021), su popolazione generale e adulti autistici con diagnosi o auto-identificati. Cut-off di ricerca ≥134: sensibilità 82,7%, specificità 79,0%. Struttura confermata nel 2025. Limite: non è stato confrontato con diagnosi cliniche.',
    stampNote_catq: 'Hull et al. (2019). Misura il camouflaging, cioè le strategie con cui una persona nasconde o compensa i tratti autistici in compagnia, per esempio imitando gli altri o preparando cosa dire. Non ha una soglia diagnostica. Va letto insieme agli altri test: chi si maschera molto può avere punteggi bassi anche con tratti autistici.',
    stampNote_cpt: 'Deriva dal Continuous Performance Test di Rosvold et al. (1956). Questa versione da 60 secondi non ha dati normativi: tempi di reazione ed errori non vanno confrontati con valori clinici.',
    stampNote_social: 'Paradigma di Klin et al. (2002) e Jones e Klin (2013), che usavano eye tracker da laboratorio. Qui la risposta è auto-riferita o stimata dalla webcam, con precisione molto inferiore: non è uno strumento validato.',
    stampNote_webcam: 'Ammiccamento (EAR, Soukupová e Čech 2016) e stabilità dello sguardo stimati dalla webcam. Le norme sul blink rate vengono da Bentivoglio et al. (1997), ma la misura non è validata come screening per autismo o ADHD.',
    stamp_valid:       'Validato',
    stamp_trait:       'Misura di tratto',
    stamp_exp:         'Sperimentale',
    stampTip_valid:    'Screener con soglia pubblicata e accuratezza misurata contro diagnosi cliniche. L\'anno è quello dello studio di validazione.',
    stampTip_trait:    'Misura validata dei tratti, ma senza soglia diagnostica clinica: cut-off solo di ricerca o assente.',
    stampTip_exp:      'Paradigma tratto dalla letteratura, ma questa versione non è validata né normata: risultati solo indicativi.',
    // CATI
    catiMeta:          '42 domande · ~7 min · ASD',
    catiShort:         'Inventario moderno (2021) dei tratti autistici in 6 aree, inclusi camouflaging e sensorialità.',
    catiInstr:         'Indica quanto sei d\'accordo con ogni affermazione pensando a come sei di solito. Non esistono risposte giuste o sbagliate.',
    catiBlockName:     'CATI · Tratti autistici',
    catiSection:       'CATI:',
    catiLow:           (s) => `Punteggio ${s}/210, sotto il cut-off di ricerca di 134. Profilo più vicino a quello medio degli adulti non autistici (English et al. 2021).`,
    catiHigh:          (s) => `Punteggio ${s}/210, pari o sopra il cut-off di ricerca di 134 (sensibilità 83%, specificità 79%). Profilo più vicino a quello medio degli adulti autistici. Il cut-off non è diagnostico (English et al. 2021).`,
    catiSubscales:     (o) => `Interazione sociale ${o.social}/35 · Comunicazione ${o.communication}/35 · Camouflaging ${o.camouflage}/35 · Comportamenti autoregolatori ${o.selfReg}/35 · Flessibilità cognitiva ${o.flexibility}/35 · Sensorialità ${o.sensory}/35`,
    catiProfileHigh:   ' Il CATI, lo strumento più recente della batteria, è sopra il cut-off di ricerca.',
    catiProfileLow:    ' Il CATI, lo strumento più recente della batteria, è sotto il cut-off di ricerca.',
    asrsContNote:      (s) => `Punteggio continuo Parte A ${s}/24 (soglia alternativa ≥14, aggiornamento Harvard 2024).`,
    // Gaze (WebGazer)
    gazeExtLabel:      'Misura lo sguardo con la webcam (sperimentale)',
    gazeIntro:         'La webcam stimerà dove guardi quando compare il volto. Serve una breve calibrazione: clicca 5 volte ciascuno dei 9 punti guardandolo fisso. Il video resta sul tuo dispositivo.',
    gazeStartBtn:      'Attiva webcam',
    gazeCalibBtn:      'Avvia calibrazione',
    gazePositionHint:  'Centra il viso nel riquadro in alto a sinistra finché diventa verde, poi avvia la calibrazione.',
    gazeSkipBtn:       'Continua senza webcam',
    gazeLoading:       'Caricamento del modello di tracciamento...',
    gazeFailed:        'Webcam non disponibile, il test prosegue con l\'auto-valutazione.',
    gazeCalibInstr:    'Guarda ogni punto rosso e cliccalo 5 volte finché scompare. Tieni la testa ferma e il viso ben illuminato.',
    gazeCheckInstr:    'Fissa il punto al centro per qualche secondo.',
    gazeResult:        (first, n, dwell, prec) => `Sguardo misurato (webcam, sperimentale) · primo sguardo sugli occhi in ${first}/${n} volti · tempo sugli occhi ${dwell === null ? 'n/d' : dwell + '%'}${prec ? ` · errore medio di calibrazione circa ${prec}px` : ''}.${prec && prec > GAZE_MAX_ERROR_PX ? ' Calibrazione poco precisa: questi valori non sono affidabili.' : ''}`,
    cptShort:          '60 secondi in cui premi solo alla X. Misura impulsività e attenzione sostenuta.',
    socialShort:       'Dove guardi per prima? La risposta potrebbe sorprenderti.',
    webcamShort:       'La webcam misura quante volte sbatti le palpebre e quanto resta stabile il tuo sguardo. 45 secondi.',
    socialTestName:    'Attenzione Sociale',
    webcamTestName:    'Eye Tracking',
    screeningIncludes: 'Cosa include questo screening:',
    aq10Desc:          '🧩 <strong>AQ-10</strong> — Autism Spectrum Quotient, versione breve (Baron-Cohen 2001/2012)',
    asrsDesc:          '⚡ <strong>ASRS-v1.1 Parte A</strong> — Self-report ADHD validato dall\'OMS (Kessler et al. 2005)',
    raadsDesc:         '🔍 <strong>RAADS-14</strong> — Ritvo Autism Asperger Diagnostic Scale, breve validata (Eriksson 2013)',
    catqDesc:          '🎭 <strong>CAT-Q</strong> — Camouflaging Autistic Traits Questionnaire (Hull et al. 2019, opzionale)',
    cptDesc:           '🎯 <strong>Task CPT</strong> — Continuous Performance Test, misura attenzione e impulsività',
    eyeDesc:           '👁️ <strong>Eye Tracking</strong> — Analisi blink rate via webcam con MediaPipe (opzionale)',
    duration:          'Durata stimata: <strong>15–25 minuti</strong>',
    startBtn:          'Inizia lo screening →',
    // AQ-10
    badgeAq10:  'AQ-10 · Autism Spectrum Quotient',
    badgeAq50:  'AQ-50 · Autism Spectrum Quotient',
    badgeAsrs18: 'ASRS-v1.1 Completo · ADHD',
    questionOf: (n, tot) => `Domanda ${n} di ${tot}`,
    prevBtn:    '← Indietro',
    nextBtn:    'Avanti →',
    finishBtn:  'Fine →',
    // ASRS
    badgeAsrs: 'ASRS-v1.1 Parte A · ADHD',
    asrs18Instr: 'Versione completa 18 domande (Parti A+B). La Parte A è lo screener clinico validato; la Parte B aggiunge informazioni dimensionali.',
    // RAADS-14
    badgeRaads:   'RAADS-14 · Ritvo Autism Scale',
    raadsInstr:   'Per ogni frase, scegli <strong>quando è stata vera per te</strong>. Fidati del primo istinto — non esistono risposte giuste o sbagliate.',
    raadsNote:    'Derivato dal RAADS-R (Ritvo et al. 2011). Tre fattori: difficoltà di mentalizzazione, ansia sociale, reattività sensoriale. Soglia di screening: ≥14/42 (Eriksson 2013).',
    // CAT-Q
    badgeCatq:    'CAT-Q · Camouflaging Autistic Traits',
    catqInstr:    'Quanto ti descrive ogni affermazione? Usa la scala da <strong>1</strong> (per niente) a <strong>7</strong> (moltissimo).',
    catqNote:     'Il CAT-Q misura il camouflaging — le strategie usate per nascondere o compensare tratti autistici nelle interazioni sociali (Hull et al. 2019). Non esiste una soglia diagnostica validata: 100/175 è solo un riferimento informale, la media riportata negli adulti autistici è circa 124.',
    catqSkipBtn:  'Salta questo test →',
    catqAgree:    'Fortemente d\'accordo',
    catqDisagree: 'Fortemente in disaccordo',
    // Restore banner
    restoreBannerText: 'Sessione precedente trovata — vuoi ripristinare i tuoi dati?',
    restoreDate:       (d) => `Salvata il ${d}`,
    restoreYes:        'Ripristina',
    restoreNo:         'Ignora',
    // CPT
    badgeCpt:      'Task · CPT',
    cptTitle:      'Continuous Performance Test',
    cptInstr:      'Lettere lampeggeranno velocemente sullo schermo. Premi <span class="cpt-key-hint">SPAZIO</span> o il bottone <strong>solo quando vedi la X</strong> — per tutto il resto, non fare nulla. Sembra semplice, ma diventa abbastanza impegnativo!',
    cptNote:       'Sessanta secondi di attenzione pura. I falsi allarmi rivelano impulsività; le mancate risposte rivelano difficoltà di attenzione sostenuta.',
    cptReady:      'Pronto? Clicca "Inizia" per cominciare.',
    cptStart:      'Inizia il test →',
    cptTap:        'Clicca qui',
    cptCorrect:    'Corretti',
    cptFA:         'Falsi allarmi',
    cptPressSpace: '← Premi SPAZIO!',
    cptDontPress:  'Non premere...',
    cptDone:       'Test completato!',
    cptBadgeDone:  'CPT · Completato ✓',
    cptResultTitle:'Risultati CPT',
    cptHitRate:    'Hit rate',
    cptFalseAlarms:'Falsi allarmi',
    cptRtMedio:    'RT medio',
    cptLateHits:   'Quasi giusti',
    cptSaved:      'Dati salvati per il report finale.',
    // Social attention
    badgeSocial:      'Task · Attenzione Sociale',
    socialTitle:      'Dove guardi per prima cosa?',
    socialInstr:      'Leggi il testo in modo naturale. Un volto apparirà brevemente da solo — poi dimmi <strong>dove hai guardato per primo</strong>.',
    socialNote:       'Basato sul paradigma "first saccade" — Klin et al. (2002) hanno documentato differenze nell\'attenzione alla regione degli occhi tra persone autistiche e non autistiche.',
    trialOf:          (n, tot) => `Trial ${n} / ${tot}`,
    readLabel:        '📖 Leggi il testo qui sotto:',
    readHint:         'Il volto apparirà a breve in modo automatico — continua a leggere normalmente.',
    faceOf:           (n, tot) => `Volto ${n} di ${tot}`,
    whereFirst:       'Dove hai guardato per prima?',
    regionEyes:       '👀 Occhi',
    regionNose:       '👃 Naso',
    regionMouth:      '👄 Bocca',
    regionOther:      '🔲 Altro',
    regionElsewhere:  '↩ Guardavo da un\'altra parte',
    socialDistracted: '↩ Mi sono distratto — ripeti',
    socialDoneText:   (pct, seen, sk) => `Test completato! ${pct}% delle prime fissazioni erano verso gli occhi (su ${seen} volti visti${sk > 0 ? `, ${sk} saltati` : ''}).`,
    socialSaved:      'Dati salvati per il report finale.',
    socialNotRead:    (n) => `${n} visi guardati mentre eri distratto/a durante la lettura.`,
    socialAllElsewhere: 'Nessun volto esaminato direttamente (tutte le risposte erano "guardavo altrove").',
    continueWebcam:   'Continua → Eye Tracking (opzionale)',
    goToResults:      'Continua → Risultati',
    // Webcam
    badgeWebcam:   'Eye Tracking · MediaPipe FaceMesh',
    webcamTitle:   'Analisi Blink Rate e Sguardo via Webcam',
    webcamDesc:    'La webcam rileva i landmark facciali con <strong>MediaPipe FaceMesh</strong> (468 punti, iris inclusi). Misura:',
    webcamBlink:   '<strong>Blink rate</strong> — frequenza di ammiccamento (normale: 12–20/min). Valori atipici documentati in alcune condizioni neurodivergenti.',
    webcamEAR:     '<strong>Eye Aspect Ratio (EAR)</strong> — indice di apertura degli occhi (Soukupová & Čech 2016).',
    webcamGaze:    '<strong>Stabilità dello sguardo</strong> — varianza della posizione iride durante la fissazione.',
    webcamNoHTTP:  '<strong>Webcam non disponibile su file://</strong><br>I browser bloccano la webcam senza server locale. Esegui <code>start.ps1</code> nella cartella, poi apri <code>http://localhost:8080</code>.<br><br>Puoi saltare e vedere i risultati dei questionari.',
    webcamStart:       'Inizia il test →',
    webcamStartTest:   'Avvia il test →',
    webcamPreviewBtn:  'Testa la webcam',
    webcamPreviewTitle:'Anteprima webcam — immagine nitida e viso ben illuminato?',
    webcamPreviewHint: 'Se l\'immagine è chiara e il viso ben visibile, sei pronto per iniziare il test.',
    webcamPrivacy:     'La webcam non viene mai registrata — tutta l\'elaborazione avviene localmente nel browser. Nessun dato viene trasmesso.',
    webcamSetupTitle:  'Prima di iniziare:',
    webcamSetupClean:  '🧹 Pulisci la webcam (o fotocamera frontale) con un panno morbido',
    webcamSetupLight:  '💡 Siediti di fronte a una fonte di luce chiara — evita il controluce',
    webcamSetupDist:   '📱 Mantieni il dispositivo a circa 50 cm dal viso, in posizione stabile',
    webcamPhasesTitle: 'Il test si svolge in tre fasi:',
    webcamPhase1Desc:  '🎯 <strong>Taratura</strong> — Chiudi gli occhi una volta e premi un bottone; la soglia di rilevamento viene calibrata sul tuo viso',
    webcamPhase2Desc:  '📖 <strong>Fase 1 — 30 s</strong> — Leggi un testo sul micelio; si misura il blink rate naturale',
    webcamPhase3Desc:  '🔺 <strong>Fase 2 — 15 s</strong> — Fissa il centro di una forma 3D rotante; si misura la stabilità dello sguardo',
    webcamReadLabel:   'Fase 1 — Leggi normalmente:',
    webcamShapeLabel:  'Fase 2 — Fissa il centro della forma:',
    webcamSkip:        'Salta → Vai ai risultati',
    webcamCDNError:    'Impossibile caricare il modello MediaPipe (controlla la connessione internet). Puoi saltare il test webcam.',
    webcamFinishRead:  'Ho finito di leggere →',
    webcamLoading:     'Caricamento modello...',
    webcamInit:        'Inizializzazione modello...',
    webcamNoFace:      'Nessun volto rilevato',
    webcamActive:      (s) => `Rilevamento attivo — ${s}s`,
    webcamActiveRead:    (s) => `Fase 1 / 2 — Lettura attiva — ${s}s rimanenti`,
    webcamActivePursuit: (s) => `Fase 2 / 2 — Fissazione attiva — ${s}s rimanenti`,
    webcamCalibTitle:   'Taratura rilevamento blink',
    webcamCalibInstr:   'Guarda la fotocamera normalmente per qualche secondo, poi chiudi gli occhi lentamente, riaprili, e premi il bottone. Il sistema misura il tuo ammiccamento per tarare la soglia di rilevamento sul tuo viso.',
    webcamCalibBtn:     'Ho fatto → Avvia la lettura',
    webcamCalibWaiting: 'Rilevamento viso in corso...',
    webcamCalibReady:   'Viso rilevato — chiudi gli occhi e premi il bottone',
    webcamDone:        'Completato ✓',
    webcamResults:     'Vedi risultati finali →',
    blinkTotal:        'Blink totali',
    blinkPerMin:       'Blink/min',
    earMean:           'EAR medio',
    gazeStability:     'Rilevamenti sguardo',
    gazeStabLabel:     'Stabilità sguardo (Fase 2)',
    gazeStab_ok:       'Stabile',
    gazeStab_mod:      'Moderata',
    gazeStab_low:      'Instabile',
    // Results
    badgeResults:       'Risultati',
    resultsTitle:       'Report Screening Neurosviluppo',
    aq10BlockName:      'AQ-10 · Autismo',
    asrsBlockName:      'ASRS-v1.1 · ADHD',
    raads14BlockName:   'RAADS-14 · ASD Scale',
    catqBlockName:      'CAT-Q · Camouflage',
    chipLow:            'Basso',
    chipMid:            'Borderline',
    chipHigh:           'Elevato',
    faChipNone:         'Nessuno',
    faChipMod:          'Moderati',
    faChipFreq:         'Frequenti',
    cptResultBlock:     '🎯 CPT Task',
    socialResultBlock:  '👁️ Attenzione Sociale',
    webcamResultBlock:  '📹 Webcam Eye Tracking',
    profileBlock:       '📊 Profilo combinato',
    printBtn:           '🖨️ Stampa report',
    restartBtn:         '↺ Ricomincia',
    aq10Section:        '🧩 AQ-10:',
    asrsSection:        '⚡ ASRS:',
    raads14Section:     '🔍 RAADS-14:',
    catqSection:        '🎭 CAT-Q:',
    aq10Low:            'I punteggi non suggeriscono tratti autistici significativi (soglia clinica: 6/10).',
    aq10Mid:            'Alcuni tratti presenti, ma sotto la soglia clinica. Considera come si manifestano nella tua vita.',
    aq10High:           (s) => `Punteggio ${s}/10 — sopra la soglia clinica (≥6). Potrebbe valere la pena parlarne con uno specialista.`,
    aq50Low:            'I punteggi non suggeriscono tratti autistici significativi (soglia clinica: 32/50).',
    aq50Mid:            (s) => `Punteggio ${s}/50 — alcuni tratti presenti, ma sotto la soglia clinica (≥32). Considera come si manifestano nella tua vita.`,
    aq50High:           (s) => `Punteggio ${s}/50 — sopra la soglia clinica (≥32). Potrebbe valere la pena parlarne con uno specialista (Baron-Cohen 2001).`,
    asrsLow:            'I punteggi non suggeriscono ADHD significativo (soglia clinica: 4/6).',
    asrsMid:            'Punteggio borderline. Una valutazione completa ASRS-v1.1 (18 item) darebbe più chiarezza.',
    asrsHigh:           (s) => `Punteggio ${s}/6 — sopra la soglia clinica (≥4). Alta specificità per ADHD negli adulti (Kessler et al. 2005).`,
    asrs18Note:         (a, b, tot) => `Parte A: ${a}/6 positivi · Parte B: ${b}/12 positivi · Punteggio dimensionale: ${tot}/72.`,
    raads14Low:         'Punteggio sotto la soglia clinica (≥14/42). Non suggerisce tratti autistici significativi su questa scala.',
    raads14Mid:         (s) => `Punteggio ${s}/42 — sopra la soglia clinica (≥14). Screening positivo. Lo strumento ha alta sensibilità ma specificità limitata verso altre condizioni psichiatriche (Eriksson 2013).`,
    raads14High:        (s) => `Punteggio ${s}/42 — ben sopra la soglia. Tratti autistici marcati, da approfondire con una valutazione clinica. La specificità limitata dello strumento impone cautela (Eriksson 2013).`,
    raads14Domains:     (m, sa, se) => `Mentalizzazione ${m}/21 · Ansia sociale ${sa}/12 · Reattività sensoriale ${se}/9`,
    catqLow:            (s) => `Punteggio ${s}/175 — sotto il riferimento informale di 100. Camouflaging limitato riportato.`,
    catqHigh:           (s) => `Punteggio ${s}/175 — sopra il riferimento informale di 100 (soglia non validata). Camouflaging marcato. I punteggi AQ-10/RAADS-14 potrebbero sottostimare i tratti autistici reali (Hull et al. 2019).`,
    catqSubscales:      (as, co, ma) => `Assimilazione: ${as}/56 · Compensazione: ${co}/63 · Masking: ${ma}/56`,
    profileNoQuestionnaires: 'Nessun questionario completato in questa sessione. Il profilo combinato richiede almeno AQ-10, ASRS o RAADS-14.',
    profileBoth:        'Punteggi elevati sia per ASD che per ADHD. La co-occorrenza (AuDHD) è documentata nel 50–70% dei casi (Antshel et al. 2013). Una valutazione neuropsicologica può distinguere il profilo.',
    profileAsdOnly:     'Punteggi AQ-10/RAADS-14 elevati senza segnali ADHD forti. Il profilo è coerente con tratti autistici senza iperattività/impulsività marcata.',
    profileAsdMasked:   'AQ-10 basso ma RAADS-14 o CAT-Q elevati: possibile camouflaging che abbassa il punteggio AQ-10. Considera una valutazione approfondita.',
    profileRaadsOnly:   'AQ-10 nella norma ma RAADS-14 sopra soglia: possibile camouflaging nei questionari o tratti autistici che emergono su scale più ampie.',
    profileAdhdOnly:    'Punteggio ASRS elevato senza tratti autistici evidenti. Il profilo è coerente con ADHD adulto.',
    profileImpuls:      'ASRS nella norma, ma il CPT mostra falsi allarmi frequenti — possibile impulsività subclinica.',
    profileInattn:      'Hit rate CPT bassa — possibile difficoltà di attenzione sostenuta, anche senza soglia ADHD nel questionario.',
    profileNorm:        'I punteggi complessivi non raggiungono le soglie cliniche. Se hai preoccupazioni, un professionista può offrire una valutazione più approfondita.',
    cptFAHigh:          '⚠️ Falsi allarmi elevati: indicatore di impulsività. ',
    cptHitLow:          '⚠️ Hit rate bassa: difficoltà di attenzione sostenuta. ',
    cptDprimeLow:       '⚠️ d\' basso: scarsa discriminazione segnale/rumore. ',
    cptNorm:            '✓ Prestazione nella norma.',
    socialEyePct:       (pct, n) => `Prime fissazioni verso gli occhi: <strong>${pct}%</strong> (${n} facce).`,
    socialHigh:         '✓ Pattern di fissazione tipico.',
    socialMid:          'Pattern borderline — alcune prime fissazioni non verso gli occhi.',
    socialLow:          '⚠️ Meno del 40% di prime fissazioni verso gli occhi — possibile atipicità nell\'attenzione sociale (proxy semplificato).',
    blinkNorm:          (bpm, n, dur) => `Blink rate: <strong>${bpm} blink/min</strong> (${n} blink in ${dur}s). Norma adulti: 12–20/min.`,
    blinkLow:           '⚠️ Blink rate molto bassa — possibile concentrazione intensa o ipocinesia.',
    blinkHigh:          '⚠️ Blink rate elevata — possibile stress o affaticamento oculare.',
    blinkOk:            '✓ Nella norma.',
    disclaimerResult:   '<strong>⚠️ Questo non è un test clinico.</strong> AQ-10: sensibilità 88%, specificità 91% (Baron-Cohen 2001/Allison 2012). ASRS Parte A: 68.7% sens., 99.5% spec. (Kessler et al. 2005). RAADS-14: 97% sens., specificità variabile 46–95% a seconda del gruppo di confronto (Eriksson 2013). CATI: cut-off di ricerca ≥134, 83% sens., 79% spec. in un campione non clinico (English 2021). CAT-Q: riferimento normativo, non diagnostico (Hull et al. 2019). Rivolgiti a un neuropsichiatra o psicologo per una valutazione completa.',
    maskingNote:        '⚠️ Nota: il camouflaging/masking può ridurre i punteggi AQ-10 nelle persone autistiche, specialmente nelle donne (Hull et al. 2017).',
    refsTitle:          '📚 Riferimenti scientifici',
    refsShow:           '▼ Mostra riferimenti',
    refsHide:           '▲ Nascondi',
    resultsSectionQ:    'Questionari',
    resultsSectionTasks:'Task oggettivi',
  },

  en: {
    // Nav steps
    stepWelcome: '1 · Welcome', stepAq10: '2 · AQ-10', stepAsrs: '3 · ASRS',
    stepRaads:   '4 · RAADS-14', stepCatq: '5 · CAT-Q',
    stepTasks:   '6 · Tasks',    stepWebcam: '7 · Webcam', stepResults: '8 · Results',
    // Welcome screen
    badgeWelcome:      'Neurodevelopmental screening',
    appSubtitle:       'Non-clinical screening for autistic traits and ADHD in adults',
    disclaimerText:    '<strong>⚠️ Important:</strong> This tool is <em>not a diagnostic test</em>. Results are indicative and do not replace evaluation by a specialist. No data is sent to remote servers — everything stays in your browser.',
    ossNotice:         '<strong>Open source · No ads · Your data stays in your browser</strong><br>Most online tests have inaccuracies and then charge €20–80 for a report. NeuroScreen uses the same scientifically validated tools, completely free, with no data collection.',
    selectTests:       'Customise your screening:',
    durationLabel:     (min) => `Estimated duration: <strong>~${min} min</strong>`,
    aq10Meta:          '10 questions · ~3 min · ASD',
    aq50Meta:          '50 questions · ~15 min · ASD',
    asrsMeta:          '6 questions · ~2 min · ADHD',
    asrs18Meta:        '18 questions · ~6 min · ADHD',
    extendedLabel:     'Extended mode',
    extendedDesc:      'AQ-50 (50 questions, ~15 min) and full ASRS-18 (18 questions, ~6 min). Same scientifically validated tools, longer and more complete versions.',
    aqExtLabel:        'Extend to AQ-50 · 50 items · ~15 min',
    asrsExtLabel:      'Extend to ASRS-18 · 18 items · ~6 min',
    raadsMeta:         '14 questions · ~5 min · ASD',
    catqMeta:          '25 questions · ~7 min · optional',
    cptMeta:           '60 seconds · objective test',
    socialMeta:        '6 trials · ~3 min',
    webcamMeta:        '45 seconds · requires HTTP',
    aq10Short:         'Autism in 10 questions. Calibrated on adult population data. Threshold ≥6/10.',
    asrsShort:         'ADHD in 6 questions. 99.5% specificity — virtually no false positives. Threshold ≥4/6.',
    raadsShort:        'More detailed autism scale: mentalizing, social anxiety and sensory reactivity. Threshold ≥14/42.',
    catqShort:         'Measures camouflaging: how much you hide or compensate for autistic traits when you are with other people. Useful if other tests give low scores but the traits sound familiar.',
    copyrightLine:     '© 2026 scozzadroid-cpu · code licensed under <a href="https://github.com/scozzadroid-cpu/neuroscreen/blob/main/LICENSE" target="_blank" rel="noopener" class="ref-link">MIT</a> · questionnaires belong to their respective authors (<a href="https://github.com/scozzadroid-cpu/neuroscreen/blob/main/THIRD_PARTY_NOTICES.md" target="_blank" rel="noopener" class="ref-link">notices</a>)',
    stampNote_aq10: 'Allison, Auyeung and Baron-Cohen (2012) compared adults diagnosed with autism and controls. At a cut-off of ≥6, sensitivity 88% and specificity 91%. Limitation: in adults referred for specialist assessment accuracy is much lower (Ashwood 2016).',
    stampNote_aq50: 'Baron-Cohen et al. (2001) compared adults with Asperger syndrome or high-functioning autism and controls, with a cut-off of ≥32. Limitation: as with the AQ-10, it predicts diagnosis poorly in adults referred for specialist assessment (Ashwood 2016).',
    stampNote_asrs: 'Kessler et al. (2005), for the WHO, compared answers with clinical interviews. Part A: sensitivity 68.7%, specificity 99.5%. Limitation: about one in three adults with ADHD stays below the cut-off. Part B of the extended version has no validated cut-off.',
    stampNote_raads14: 'Eriksson et al. (2013), in adults seen in psychiatric care. Sensitivity 97%, but specificity 46–64% against ADHD and other psychiatric disorders (about 95% against controls). Limitation: many false positives in people with other psychiatric conditions.',
    stampNote_cati: 'English et al. (2021), in the general population and diagnosed or self-identifying autistic adults. Research cut-off ≥134: sensitivity 82.7%, specificity 79.0%. Structure confirmed in 2025. Limitation: not compared against clinical diagnoses.',
    stampNote_catq: 'Hull et al. (2019). Measures camouflaging, the strategies a person uses to hide or compensate for autistic traits around others, such as copying people or rehearsing what to say. It has no diagnostic cut-off. Read it together with the other tests: people who camouflage a lot can score low even with autistic traits.',
    stampNote_cpt: 'Derived from the Continuous Performance Test by Rosvold et al. (1956). This 60-second version has no normative data: reaction times and errors should not be compared with clinical values.',
    stampNote_social: 'Paradigm from Klin et al. (2002) and Jones and Klin (2013), who used laboratory eye trackers. Here the answer is self-reported or estimated by the webcam, with far lower precision: it is not a validated tool.',
    stampNote_webcam: 'Blinking (EAR, Soukupová and Čech 2016) and gaze stability estimated by the webcam. Blink rate norms come from Bentivoglio et al. (1997), but the measure is not validated as a screening for autism or ADHD.',
    stamp_valid:       'Validated',
    stamp_trait:       'Trait measure',
    stamp_exp:         'Experimental',
    stampTip_valid:    'Screener with a published cut-off and accuracy measured against clinical diagnoses. The year is that of the validation study.',
    stampTip_trait:    'Validated trait measure without a clinical diagnostic cut-off: research-only cut-off or none.',
    stampTip_exp:      'Paradigm taken from the literature, but this version is neither validated nor normed: results are indicative only.',
    // CATI
    catiMeta:          '42 questions · ~7 min · ASD',
    catiShort:         'Modern (2021) inventory of autistic traits across 6 areas, including camouflaging and sensory sensitivity.',
    catiInstr:         'Rate how much you agree with each statement, thinking about how you usually are. There are no right or wrong answers.',
    catiBlockName:     'CATI · Autistic traits',
    catiSection:       'CATI:',
    catiLow:           (s) => `Score ${s}/210, below the research cut-off of 134. Profile closer to the average non-autistic adult (English et al. 2021).`,
    catiHigh:          (s) => `Score ${s}/210, at or above the research cut-off of 134 (sensitivity 83%, specificity 79%). Profile closer to the average autistic adult. The cut-off is not diagnostic (English et al. 2021).`,
    catiSubscales:     (o) => `Social interactions ${o.social}/35 · Communication ${o.communication}/35 · Social camouflage ${o.camouflage}/35 · Self-regulating behaviours ${o.selfReg}/35 · Cognitive flexibility ${o.flexibility}/35 · Sensory sensitivity ${o.sensory}/35`,
    catiProfileHigh:   ' The CATI, the most recent tool in this battery, is above its research cut-off.',
    catiProfileLow:    ' The CATI, the most recent tool in this battery, is below its research cut-off.',
    asrsContNote:      (s) => `Part A continuous score ${s}/24 (alternative threshold ≥14, Harvard 2024 scoring update).`,
    // Gaze (WebGazer)
    gazeExtLabel:      'Measure gaze with the webcam (experimental)',
    gazeIntro:         'The webcam will estimate where you look when the face appears. A short calibration is needed: click each of the 9 dots 5 times while looking at it. The video stays on your device.',
    gazeStartBtn:      'Enable webcam',
    gazeCalibBtn:      'Start calibration',
    gazePositionHint:  'Centre your face in the box at the top left until it turns green, then start the calibration.',
    gazeSkipBtn:       'Continue without webcam',
    gazeLoading:       'Loading the tracking model...',
    gazeFailed:        'Webcam unavailable, the test continues with self-report.',
    gazeCalibInstr:    'Look at each red dot and click it 5 times until it disappears. Keep your head still and your face well lit.',
    gazeCheckInstr:    'Look at the dot in the centre for a few seconds.',
    gazeResult:        (first, n, dwell, prec) => `Measured gaze (webcam, experimental) · first look on the eyes in ${first}/${n} faces · time on the eyes ${dwell === null ? 'n/a' : dwell + '%'}${prec ? ` · mean calibration error about ${prec}px` : ''}.${prec && prec > GAZE_MAX_ERROR_PX ? ' Calibration was imprecise: these values are not reliable.' : ''}`,
    cptShort:          '60 seconds where you only press for X. Measures impulsivity and sustained attention.',
    socialShort:       'Where do you look first? The answer might surprise you.',
    webcamShort:       'Webcam measures how often you blink and how steady your gaze is. 45 seconds.',
    socialTestName:    'Social Attention',
    webcamTestName:    'Eye Tracking',
    screeningIncludes: 'This screening includes:',
    aq10Desc:          '🧩 <strong>AQ-10</strong> — Autism Spectrum Quotient short form (Baron-Cohen 2001/2012)',
    asrsDesc:          '⚡ <strong>ASRS-v1.1 Part A</strong> — WHO-validated ADHD self-report (Kessler et al. 2005)',
    raadsDesc:         '🔍 <strong>RAADS-14</strong> — Ritvo Autism Asperger Diagnostic Scale, validated short form (Eriksson 2013)',
    catqDesc:          '🎭 <strong>CAT-Q</strong> — Camouflaging Autistic Traits Questionnaire (Hull et al. 2019, optional)',
    cptDesc:           '🎯 <strong>CPT Task</strong> — Continuous Performance Test, measures attention and impulsivity',
    eyeDesc:           '👁️ <strong>Eye Tracking</strong> — Blink rate analysis via webcam using MediaPipe (optional)',
    duration:          'Estimated duration: <strong>15–25 minutes</strong>',
    startBtn:          'Start screening →',
    // AQ-10
    badgeAq10:  'AQ-10 · Autism Spectrum Quotient',
    badgeAq50:  'AQ-50 · Autism Spectrum Quotient',
    badgeAsrs18: 'ASRS-v1.1 Full · ADHD',
    questionOf: (n, tot) => `Question ${n} of ${tot}`,
    prevBtn:    '← Back',
    nextBtn:    'Next →',
    finishBtn:  'Finish →',
    // ASRS
    badgeAsrs: 'ASRS-v1.1 Part A · ADHD',
    asrs18Instr: 'Full 18-item version (Parts A+B). Part A is the validated clinical screener; Part B adds dimensional information.',
    // RAADS-14
    badgeRaads:   'RAADS-14 · Ritvo Autism Scale',
    raadsInstr:   'For each statement, choose <strong>when it has been true for you</strong>. Go with your first instinct — there are no right or wrong answers.',
    raadsNote:    'Derived from the RAADS-R (Ritvo et al. 2011). Three factors: mentalizing deficits, social anxiety, sensory reactivity. Screening threshold: ≥14/42 (Eriksson 2013).',
    // CAT-Q
    badgeCatq:    'CAT-Q · Camouflaging Autistic Traits',
    catqInstr:    'How much does each statement describe you? Use the scale from <strong>1</strong> (not at all) to <strong>7</strong> (completely).',
    catqNote:     'The CAT-Q measures camouflaging — strategies used to hide or compensate for autistic traits in social interactions (Hull et al. 2019). There is no validated diagnostic cut-off: 100/175 is only an informal reference point; reported mean in autistic adults is about 124.',
    catqSkipBtn:  'Skip this test →',
    catqAgree:    'Strongly agree',
    catqDisagree: 'Strongly disagree',
    // Restore banner
    restoreBannerText: 'Previous session found — would you like to restore your data?',
    restoreDate:       (d) => `Saved on ${d}`,
    restoreYes:        'Restore',
    restoreNo:         'Dismiss',
    // CPT
    badgeCpt:      'Task · CPT',
    cptTitle:      'Continuous Performance Test',
    cptInstr:      'Letters will flash quickly on screen. Hit <span class="cpt-key-hint">SPACE</span> or the button <strong>only when you see X</strong> — for everything else, do nothing. Sounds easy — it gets surprisingly tricky!',
    cptNote:       'Sixty seconds of pure focus. False alarms reveal impulsivity; misses reveal sustained-attention difficulties.',
    cptReady:      'Ready? Click "Start" to begin.',
    cptStart:      'Start test →',
    cptTap:        'Click here',
    cptCorrect:    'Correct',
    cptFA:         'False alarms',
    cptPressSpace: '← Press SPACE!',
    cptDontPress:  'Do not press...',
    cptDone:       'Test completed!',
    cptBadgeDone:  'CPT · Completed ✓',
    cptResultTitle:'CPT Results',
    cptHitRate:    'Hit rate',
    cptFalseAlarms:'False alarms',
    cptRtMedio:    'Mean RT',
    cptLateHits:   'Near misses',
    cptSaved:      'Data saved for the final report.',
    // Social attention
    badgeSocial:      'Task · Social Attention',
    socialTitle:      'Where do you look first?',
    socialInstr:      'Read the text naturally. A face will flash up briefly on its own — then tell us <strong>where you looked first</strong>.',
    socialNote:       'Based on the "first saccade" paradigm — Klin et al. (2002) documented differences in attention to the eye region between autistic and non-autistic individuals.',
    trialOf:          (n, tot) => `Trial ${n} / ${tot}`,
    readLabel:        '📖 Read the text below:',
    readHint:         'The face will appear automatically shortly — continue reading normally.',
    faceOf:           (n, tot) => `Face ${n} of ${tot}`,
    whereFirst:       'Where did you look first?',
    regionEyes:       '👀 Eyes',
    regionNose:       '👃 Nose',
    regionMouth:      '👄 Mouth',
    regionOther:      '🔲 Other',
    regionElsewhere:  '↩ I was looking elsewhere',
    socialDistracted: '↩ I got distracted — retry',
    socialDoneText:   (pct, seen, sk) => `Completed! ${pct}% of first fixations were toward the eyes (out of ${seen} faces seen${sk > 0 ? `, ${sk} skipped` : ''}).`,
    socialSaved:      'Data saved for the final report.',
    socialNotRead:    (n) => `${n} faces seen while distracted during the reading phase.`,
    socialAllElsewhere: 'No faces examined directly (all responses were "looking elsewhere").',
    continueWebcam:   'Continue → Eye Tracking (optional)',
    goToResults:      'Continue → Results',
    // Webcam
    badgeWebcam:   'Eye Tracking · MediaPipe FaceMesh',
    webcamTitle:   'Blink Rate & Gaze Analysis via Webcam',
    webcamDesc:    'The webcam detects facial landmarks using <strong>MediaPipe FaceMesh</strong> (468 points, including irises). Measures:',
    webcamBlink:   '<strong>Blink rate</strong> — blinking frequency (normal: 12–20/min). Atypical values documented in some neurodivergent conditions.',
    webcamEAR:     '<strong>Eye Aspect Ratio (EAR)</strong> — eye opening index (Soukupová & Čech 2016).',
    webcamGaze:    '<strong>Gaze stability</strong> — iris position variance during fixation.',
    webcamNoHTTP:  '<strong>Webcam unavailable on file://</strong><br>Browsers block webcam access without a local server. Run <code>start.ps1</code> in the project folder, then reopen <code>http://localhost:8080</code>.<br><br>You can skip and view questionnaire results.',
    webcamStart:       'Start test →',
    webcamStartTest:   'Start test →',
    webcamPreviewBtn:  'Test webcam',
    webcamPreviewTitle:'Webcam preview — is the image sharp and your face well lit?',
    webcamPreviewHint: 'If the image is clear and your face is visible, you are ready to start.',
    webcamPrivacy:     'The webcam is never recorded — all processing happens locally in your browser. No data is transmitted.',
    webcamSetupTitle:  'Before you start:',
    webcamSetupClean:  '🧹 Clean the webcam (or front camera) with a soft cloth',
    webcamSetupLight:  '💡 Sit in front of a clear light source — avoid backlighting',
    webcamSetupDist:   '📱 Hold the device about 50 cm from your face, steady',
    webcamPhasesTitle: 'The test has three phases:',
    webcamPhase1Desc:  '🎯 <strong>Calibration</strong> — Close your eyes once and press a button; the detection threshold is tuned to your face',
    webcamPhase2Desc:  '📖 <strong>Phase 1 — 30 s</strong> — Read a text about mycelium; natural blink rate is measured',
    webcamPhase3Desc:  '🔺 <strong>Phase 2 — 15 s</strong> — Fixate on the centre of a rotating 3D shape; gaze stability is measured',
    webcamReadLabel:   'Phase 1 — Read normally:',
    webcamShapeLabel:  'Phase 2 — Fixate on the centre of the shape:',
    webcamSkip:        'Skip → Go to results',
    webcamCDNError:    'Could not load the MediaPipe model (check your internet connection). You can skip the webcam test.',
    webcamFinishRead:  'Done reading →',
    webcamLoading:     'Loading model...',
    webcamInit:        'Initialising model...',
    webcamNoFace:      'No face detected',
    webcamActive:      (s) => `Detection active — ${s}s`,
    webcamActiveRead:    (s) => `Phase 1 / 2 — Reading active — ${s}s remaining`,
    webcamActivePursuit: (s) => `Phase 2 / 2 — Fixation active — ${s}s remaining`,
    webcamCalibTitle:   'Blink detection calibration',
    webcamCalibInstr:   'Look at the camera normally for a few seconds, then slowly close your eyes, reopen them, and press the button. The system measures your natural blink to calibrate the detection threshold for your face.',
    webcamCalibBtn:     'Done → Start reading',
    webcamCalibWaiting: 'Detecting face...',
    webcamCalibReady:   'Face detected — close your eyes and press the button',
    webcamDone:        'Completed ✓',
    webcamResults:     'View final results →',
    blinkTotal:        'Total blinks',
    blinkPerMin:       'Blinks/min',
    earMean:           'Mean EAR',
    gazeStability:     'Gaze detections',
    gazeStabLabel:     'Gaze stability (Phase 2)',
    gazeStab_ok:       'Stable',
    gazeStab_mod:      'Moderate',
    gazeStab_low:      'Unstable',
    // Results
    badgeResults:       'Results',
    resultsTitle:       'Neurodevelopmental Screening Report',
    aq10BlockName:      'AQ-10 · Autism',
    asrsBlockName:      'ASRS-v1.1 · ADHD',
    raads14BlockName:   'RAADS-14 · ASD Scale',
    catqBlockName:      'CAT-Q · Camouflage',
    chipLow:            'Low',
    chipMid:            'Borderline',
    chipHigh:           'High',
    faChipNone:         'None',
    faChipMod:          'Moderate',
    faChipFreq:         'Frequent',
    cptResultBlock:     '🎯 CPT Task',
    socialResultBlock:  '👁️ Social Attention',
    webcamResultBlock:  '📹 Webcam Eye Tracking',
    profileBlock:       '📊 Combined profile',
    printBtn:           '🖨️ Print report',
    restartBtn:         '↺ Restart',
    aq10Section:        '🧩 AQ-10:',
    asrsSection:        '⚡ ASRS:',
    raads14Section:     '🔍 RAADS-14:',
    catqSection:        '🎭 CAT-Q:',
    aq10Low:            'Scores do not suggest significant autistic traits (clinical threshold: 6/10).',
    aq10Mid:            'Some traits present, but below the clinical threshold. Consider how these manifest in your daily life.',
    aq10High:           (s) => `Score ${s}/10 — above the clinical threshold (≥6). It may be worth discussing this with a specialist.`,
    aq50Low:            'Scores do not suggest significant autistic traits (clinical threshold: 32/50).',
    aq50Mid:            (s) => `Score ${s}/50 — some traits present, but below the clinical threshold (≥32). Consider how these manifest in your daily life.`,
    aq50High:           (s) => `Score ${s}/50 — above the clinical threshold (≥32). It may be worth discussing this with a specialist (Baron-Cohen 2001).`,
    asrsLow:            'Scores do not suggest significant ADHD (clinical threshold: 4/6).',
    asrsMid:            'Borderline score. A full ASRS-v1.1 (18-item) assessment would provide more clarity.',
    asrsHigh:           (s) => `Score ${s}/6 — above the clinical threshold (≥4). High specificity for predicting ADHD in adults (Kessler et al. 2005).`,
    asrs18Note:         (a, b, tot) => `Part A: ${a}/6 positive · Part B: ${b}/12 positive · Dimensional score: ${tot}/72.`,
    raads14Low:         'Score below the clinical threshold (≥14/42). Does not suggest significant autistic traits on this scale.',
    raads14Mid:         (s) => `Score ${s}/42 — above the clinical threshold (≥14). Positive screen. The tool has high sensitivity but limited specificity against other psychiatric conditions (Eriksson 2013).`,
    raads14High:        (s) => `Score ${s}/42 — well above threshold. Marked autistic traits that warrant a clinical assessment. Limited specificity calls for caution (Eriksson 2013).`,
    raads14Domains:     (m, sa, se) => `Mentalizing ${m}/21 · Social anxiety ${sa}/12 · Sensory reactivity ${se}/9`,
    catqLow:            (s) => `Score ${s}/175 — below the informal reference of 100. Limited camouflaging reported.`,
    catqHigh:           (s) => `Score ${s}/175 — above the informal reference of 100 (not a validated cut-off). Marked camouflaging. AQ-10/RAADS-14 scores may underestimate true autistic traits (Hull et al. 2019).`,
    catqSubscales:      (as, co, ma) => `Assimilation: ${as}/56 · Compensation: ${co}/63 · Masking: ${ma}/56`,
    profileNoQuestionnaires: 'No questionnaires completed in this session. A combined profile requires at least AQ-10, ASRS or RAADS-14.',
    profileBoth:        'High scores for both ASD and ADHD. Co-occurrence (AuDHD) is documented in 50–70% of cases (Antshel et al. 2013). A neuropsychological evaluation can distinguish the profile.',
    profileAsdOnly:     'Elevated AQ-10/RAADS-14 without strong ADHD signals. The profile is consistent with autistic traits without marked hyperactivity/impulsivity.',
    profileAsdMasked:   'Low AQ-10 but elevated RAADS-14 or CAT-Q: possible camouflaging lowering the AQ-10 score. Consider a thorough evaluation.',
    profileRaadsOnly:   'AQ-10 within normal range but RAADS-14 above threshold: possible camouflaging on questionnaires, or autistic traits emerging on broader scales.',
    profileAdhdOnly:    'High ASRS score without evident autistic traits. The profile is consistent with adult ADHD.',
    profileImpuls:      'ASRS within normal range, but CPT shows frequent false alarms — possible subclinical impulsivity.',
    profileInattn:      'Low CPT hit rate — possible sustained attention difficulties, without reaching the ADHD questionnaire threshold.',
    profileNorm:        'Overall scores do not reach clinical thresholds. If you have concerns, a professional can offer a more thorough evaluation.',
    cptFAHigh:          '⚠️ High false alarms: indicator of impulsivity. ',
    cptHitLow:          '⚠️ Low hit rate: sustained attention difficulties. ',
    cptDprimeLow:       '⚠️ Low d\': poor signal/noise discrimination. ',
    cptNorm:            '✓ Performance within normal range.',
    socialEyePct:       (pct, n) => `First fixations toward eyes: <strong>${pct}%</strong> (${n} faces).`,
    socialHigh:         '✓ Typical fixation pattern.',
    socialMid:          'Borderline pattern — some first fixations not toward the eyes.',
    socialLow:          '⚠️ Less than 40% of first fixations toward the eyes — may indicate atypicality in social attention (simplified proxy).',
    blinkNorm:          (bpm, n, dur) => `Blink rate: <strong>${bpm} blinks/min</strong> (${n} blinks in ${dur}s). Adult norm: 12–20/min.`,
    blinkLow:           '⚠️ Very low blink rate — possible intense concentration or hypokinesia.',
    blinkHigh:          '⚠️ Elevated blink rate — possible stress or eye fatigue.',
    blinkOk:            '✓ Within normal range.',
    disclaimerResult:   '<strong>⚠️ This is not a clinical test.</strong> AQ-10: 88% sensitivity, 91% specificity (Baron-Cohen 2001/Allison 2012). ASRS Part A: 68.7% sens., 99.5% spec. (Kessler et al. 2005). RAADS-14: 97% sens., specificity varies 46–95% depending on the comparison group (Eriksson 2013). CATI: research cut-off ≥134, 83% sens., 79% spec. in a non-clinical sample (English 2021). CAT-Q: normative reference, not diagnostic (Hull et al. 2019). Please consult a neuropsychiatrist or psychologist for a full evaluation.',
    maskingNote:        '⚠️ Note: camouflaging/masking can lower AQ-10 scores in autistic individuals, especially women (Hull et al. 2017).',
    refsTitle:          '📚 Scientific References',
    refsShow:           '▼ Show references',
    refsHide:           '▲ Hide',
    resultsSectionQ:    'Questionnaires',
    resultsSectionTasks:'Objective tasks',
  },
};
