'use strict';
// ════════════════════════════════════════════════════════
//  UI TRANSLATIONS — all display strings for IT and EN
// ════════════════════════════════════════════════════════

const UI = {
  it: {
    // Nav steps
    stepWelcome: '1 · Benvenuto', stepAq10: '2 · AQ-10', stepAsrs: '3 · ASRS',
    stepRaads:   '4 · RAADS-14',  stepCatq:  '5 · CAT-Q',
    stepTasks:   '6 · Task',      stepWebcam: '7 · Webcam', stepResults: '8 · Risultati',
    // Welcome screen
    badgeWelcome:      'Screening neurosviluppo',
    appSubtitle:       'Screening non clinico per tratti autistici e ADHD negli adulti',
    disclaimerText:    '<strong>⚠️ Importante:</strong> Questo strumento <em>non è un test diagnostico</em>. I risultati sono indicativi e non sostituiscono la valutazione di uno specialista. Nessun dato viene inviato a server remoti — tutto rimane nel tuo browser.',
    ossNotice:         '<strong>Open source · Zero pubblicità · I tuoi dati restano nel browser</strong><br>La maggior parte dei test online ha imprecisioni e poi propone report a €20–80. NeuroScreen usa gli stessi strumenti validati scientificamente, completamente gratuiti, senza raccogliere alcun dato.',
    selectTests:       'Personalizza lo screening:',
    durationLabel:     (min) => `Durata stimata: <strong>~${min} min</strong>`,
    aq10Meta:          '10 domande · ~3 min · ASD',
    asrsMeta:          '6 domande · ~2 min · ADHD',
    raadsMeta:         '14 domande · ~5 min · ASD',
    catqMeta:          '25 domande · ~7 min · opzionale',
    cptMeta:           '60 secondi · test obiettivo',
    socialMeta:        '6 trial · ~3 min',
    webcamMeta:        '45 secondi · richiede HTTP',
    aq10Short:         'Autism Spectrum Quotient breve. Soglia ≥6/10. Specificità ~84% (Baron-Cohen 2012).',
    asrsShort:         'Self-report ADHD validato OMS. Soglia ≥4/6. Specificità 99.5% (Kessler 2005).',
    raadsShort:        'Scala autism dettagliata. 4 domini cognitivi. Sens. ~91%, spec. ~84% (Eriksson 2013).',
    catqShort:         'Misura il camouflaging autistico. Fondamentale per donne e late-diagnosed (Hull 2019).',
    cptShort:          'Test obiettivo di attenzione sostenuta e impulsività (Rosvold 1956; Conners 2004).',
    socialShort:       'Dove guardi per prima? Paradigma "first saccade" con volti SVG (Klin 2002).',
    webcamShort:       'Test 2 fasi (45 s): blink rate durante la lettura + stabilità sguardo su forma 3D. Richiede HTTP.',
    socialTestName:    'Attenzione Sociale',
    webcamTestName:    'Eye Tracking',
    screeningIncludes: 'Cosa include questo screening:',
    aq10Desc:          '🧩 <strong>AQ-10</strong> — Autism Spectrum Quotient, versione breve (Baron-Cohen 2001/2012)',
    asrsDesc:          '⚡ <strong>ASRS-v1.1 Parte A</strong> — Self-report ADHD validato dall\'OMS (Kessler et al. 2005)',
    raadsDesc:         '🔍 <strong>RAADS-14</strong> — Ritvo Autism Asperger Diagnostic Scale, breve validata (Eriksson 2013)',
    catqDesc:          '🎭 <strong>CAT-Q</strong> — Camouflaging Autistic Traits Questionnaire (Hull et al. 2019, opzionale)',
    cptDesc:           '🎯 <strong>Task CPT</strong> — Continuous Performance Test, misura attenzione e impulsività',
    eyeDesc:           '👁️ <strong>Eye Tracking</strong> — Analisi blink rate via webcam con MediaPipe (opzionale)',
    duration:          'Durata stimata: <strong>15–25 minuti</strong>',
    startBtn:          'Inizia lo screening →',
    // AQ-10
    badgeAq10:  'AQ-10 · Autism Spectrum Quotient',
    questionOf: (n, tot) => `Domanda ${n} di ${tot}`,
    prevBtn:    '← Indietro',
    nextBtn:    'Avanti →',
    finishBtn:  'Fine →',
    // ASRS
    badgeAsrs: 'ASRS-v1.1 Parte A · ADHD',
    // RAADS-14
    badgeRaads:   'RAADS-14 · Ritvo Autism Scale',
    raadsInstr:   'Per ogni affermazione, scegli <strong>quando è stata vera per te</strong>. Non ci sono risposte giuste o sbagliate.',
    raadsNote:    'Basato sul RAADS-R (Ritvo et al. 2011). Misura tratti autistici in 4 domini: Linguaggio, Relazioni sociali, Sensorio-motorio, Interessi circoscritti. Soglia clinica: ≥14/42 (Eriksson 2013).',
    // CAT-Q
    badgeCatq:    'CAT-Q · Camouflaging Autistic Traits',
    catqInstr:    'Indica quanto sei d\'accordo con ogni affermazione su una scala da <strong>1</strong> (fortemente in disaccordo) a <strong>7</strong> (fortemente d\'accordo).',
    catqNote:     'Il CAT-Q misura il camouflaging — le strategie usate per nascondere o compensare tratti autistici nelle interazioni sociali (Hull et al. 2019). Punteggio totale ≥100/175 indica camouflaging significativo.',
    catqSkipBtn:  'Salta questo test →',
    catqAgree:    'Fortemente d\'accordo',
    catqDisagree: 'Fortemente in disaccordo',
    // Restore banner
    restoreBannerText: 'Sessione precedente trovata — vuoi ripristinare i tuoi dati?',
    restoreDate:       (d) => `Salvata il ${d}`,
    restoreYes:        'Ripristina',
    restoreNo:         'Ignora',
    // CPT
    badgeCpt:      'Task · CPT',
    cptTitle:      'Continuous Performance Test',
    cptInstr:      'Vengono visualizzate lettere in rapida successione. Premi <span class="cpt-key-hint">SPAZIO</span> (o il bottone) <strong>solo quando vedi la lettera X</strong>. Per tutte le altre lettere, non fare nulla.',
    cptNote:       'Il test dura 60 secondi. Misura attenzione sostenuta e impulsività — marker rilevanti per ADHD (Conners 2004; Rosvold et al. 1956).',
    cptReady:      'Pronto? Clicca "Inizia" per cominciare.',
    cptStart:      'Inizia il test →',
    cptTap:        'TAP / SPAZIO',
    cptCorrect:    'Corretti',
    cptFA:         'Falsi allarmi',
    cptPressSpace: '← Premi SPAZIO!',
    cptDontPress:  'Non premere...',
    cptDone:       'Test completato!',
    cptBadgeDone:  'CPT · Completato ✓',
    cptResultTitle:'Risultati CPT',
    cptHitRate:    'Hit rate',
    cptFalseAlarms:'Falsi allarmi',
    cptRtMedio:    'RT medio',
    cptSaved:      'Dati salvati per il report finale.',
    // Social attention
    badgeSocial:      'Task · Attenzione Sociale',
    socialTitle:      'Dove guardi per prima cosa?',
    socialInstr:      'Ti verrà mostrato un volto per un breve momento. Poi indica <strong>dove hai guardato per prima</strong>.',
    socialNote:       'Basato sul paradigma "first saccade" — Klin et al. (2002) hanno documentato differenze nell\'attenzione alla regione degli occhi tra persone autistiche e non autistiche.',
    trialOf:          (n, tot) => `Trial ${n} / ${tot}`,
    readLabel:        '📖 Leggi il testo qui sotto:',
    readHint:         'Il volto apparirà a breve in modo automatico — continua a leggere normalmente.',
    faceOf:           (n, tot) => `Volto ${n} di ${tot}`,
    whereFirst:       'Dove hai guardato per prima?',
    regionEyes:       '👀 Occhi',
    regionNose:       '👃 Naso',
    regionMouth:      '👄 Bocca',
    regionOther:      '🔲 Altro',
    regionElsewhere:  '↩ Guardavo da un\'altra parte',
    socialDoneText:   (pct, seen, sk) => `Test completato! ${pct}% delle prime fissazioni erano verso gli occhi (su ${seen} volti visti${sk > 0 ? `, ${sk} saltati` : ''}).`,
    socialSaved:      'Dati salvati per il report finale.',
    continueWebcam:   'Continua → Eye Tracking (opzionale)',
    goToResults:      'Continua → Risultati',
    // Webcam
    badgeWebcam:   'Eye Tracking · MediaPipe FaceMesh',
    webcamTitle:   'Analisi Blink Rate e Sguardo via Webcam',
    webcamDesc:    'La webcam rileva i landmark facciali con <strong>MediaPipe FaceMesh</strong> (468 punti, iris inclusi). Misura:',
    webcamBlink:   '<strong>Blink rate</strong> — frequenza di ammiccamento (normale: 12–20/min). Valori atipici documentati in alcune condizioni neurodivergenti.',
    webcamEAR:     '<strong>Eye Aspect Ratio (EAR)</strong> — indice di apertura degli occhi (Soukupová & Čech 2016).',
    webcamGaze:    '<strong>Stabilità dello sguardo</strong> — varianza della posizione iride durante la fissazione.',
    webcamNoHTTP:  '<strong>Webcam non disponibile su file://</strong><br>I browser bloccano la webcam senza server locale. Esegui <code>start.ps1</code> nella cartella, poi apri <code>http://localhost:8080</code>.<br><br>Puoi saltare e vedere i risultati dei questionari.',
    webcamStart:       'Inizia il test →',
    webcamStartTest:   'Avvia il test →',
    webcamPreviewBtn:  'Testa la webcam',
    webcamPreviewTitle:'Anteprima webcam — immagine nitida e viso ben illuminato?',
    webcamPreviewHint: 'Se l\'immagine è chiara e il viso ben visibile, sei pronto per iniziare il test.',
    webcamPrivacy:     'La webcam non viene mai registrata — tutta l\'elaborazione avviene localmente nel browser. Nessun dato viene trasmesso.',
    webcamSetupTitle:  'Prima di iniziare:',
    webcamSetupClean:  '🧹 Pulisci la webcam (o fotocamera frontale) con un panno morbido',
    webcamSetupLight:  '💡 Siediti di fronte a una fonte di luce chiara — evita il controluce',
    webcamSetupDist:   '📱 Mantieni il dispositivo a circa 50 cm dal viso, in posizione stabile',
    webcamPhasesTitle: 'Il test si svolge in due fasi:',
    webcamPhase1Desc:  '📖 <strong>Fase 1 — 30 s</strong> — Leggi un testo sul micelio; si misura il blink rate naturale',
    webcamPhase2Desc:  '🔺 <strong>Fase 2 — 15 s</strong> — Fissa il centro di una forma 3D rotante; si misura la stabilità dello sguardo',
    webcamReadLabel:   'Fase 1 — Leggi normalmente:',
    webcamShapeLabel:  'Fase 2 — Fissa il centro della forma:',
    webcamSkip:        'Salta → Vai ai risultati',
    webcamLoading:     'Caricamento modello...',
    webcamInit:        'Inizializzazione modello...',
    webcamNoFace:      'Nessun volto rilevato',
    webcamActive:      (s) => `Rilevamento attivo — ${s}s`,
    webcamActiveRead:    (s) => `Fase 1 / 2 — Lettura attiva — ${s}s rimanenti`,
    webcamActivePursuit: (s) => `Fase 2 / 2 — Fissazione attiva — ${s}s rimanenti`,
    webcamDone:        'Completato ✓',
    webcamResults:     'Vedi risultati finali →',
    blinkTotal:        'Blink totali',
    blinkPerMin:       'Blink/min',
    earMean:           'EAR medio',
    gazeStability:     'Rilevamenti sguardo',
    gazeStabLabel:     'Stabilità sguardo (Fase 2)',
    gazeStab_ok:       'Stabile',
    gazeStab_mod:      'Moderata',
    gazeStab_low:      'Instabile',
    // Results
    badgeResults:       'Risultati',
    resultsTitle:       'Report Screening Neurosviluppo',
    aq10BlockName:      'AQ-10 · Autismo',
    asrsBlockName:      'ASRS-v1.1 · ADHD',
    raads14BlockName:   'RAADS-14 · ASD Scale',
    catqBlockName:      'CAT-Q · Camouflage',
    chipLow:            'Basso',
    chipMid:            'Borderline',
    chipHigh:           'Elevato',
    faChipNone:         'Nessuno',
    faChipMod:          'Moderati',
    faChipFreq:         'Frequenti',
    cptResultBlock:     '🎯 CPT Task',
    socialResultBlock:  '👁️ Attenzione Sociale',
    webcamResultBlock:  '📹 Webcam Eye Tracking',
    profileBlock:       '📊 Profilo combinato',
    printBtn:           '🖨️ Stampa report',
    restartBtn:         '↺ Ricomincia',
    aq10Section:        '🧩 AQ-10:',
    asrsSection:        '⚡ ASRS:',
    raads14Section:     '🔍 RAADS-14:',
    catqSection:        '🎭 CAT-Q:',
    aq10Low:            'I punteggi non suggeriscono tratti autistici significativi (soglia clinica: 6/10).',
    aq10Mid:            'Alcuni tratti presenti, ma sotto la soglia clinica. Considera come si manifestano nella tua vita.',
    aq10High:           (s) => `Punteggio ${s}/10 — sopra la soglia clinica (≥6). Potrebbe valere la pena parlarne con uno specialista.`,
    asrsLow:            'I punteggi non suggeriscono ADHD significativo (soglia clinica: 4/6).',
    asrsMid:            'Punteggio borderline. Una valutazione completa ASRS-v1.1 (18 item) darebbe più chiarezza.',
    asrsHigh:           (s) => `Punteggio ${s}/6 — sopra la soglia clinica (≥4). Alta specificità per ADHD negli adulti (Kessler 2005).`,
    raads14Low:         'Punteggio sotto la soglia clinica (≥14/42). Non suggerisce tratti autistici significativi su questa scala.',
    raads14Mid:         (s) => `Punteggio ${s}/42 — sopra la soglia clinica (≥14). Tratti autistici rilevanti in almeno un dominio. Consistente con ASD adulto (Eriksson 2013).`,
    raads14High:        (s) => `Punteggio ${s}/42 — ben sopra la soglia. Presenza marcata di tratti autistici in più domini. Alta probabilità di ASD (Eriksson 2013).`,
    raads14Domains:     'Domini: Linguaggio · Relazioni sociali · Sensorio-motorio · Interessi circoscritti',
    catqLow:            (s) => `Punteggio ${s}/175 — sotto la soglia (≥100). Camouflaging limitato riportato.`,
    catqHigh:           (s) => `Punteggio ${s}/175 — sopra la soglia (≥100). Camouflaging significativo. I punteggi AQ-10/RAADS-14 potrebbero sottostimare i tratti autistici reali (Hull et al. 2019).`,
    catqSubscales:      (ma, as, co) => `Masking: ${ma}/63 · Assimilazione: ${as}/63 · Compensazione: ${co}/49`,
    profileBoth:        'Punteggi elevati sia per ASD che per ADHD. La co-occorrenza (AuDHD) è documentata nel 50–70% dei casi (Antshel et al. 2013). Una valutazione neuropsicologica può distinguere il profilo.',
    profileAsdOnly:     'Punteggi AQ-10/RAADS-14 elevati senza segnali ADHD forti. Il profilo è coerente con tratti autistici senza iperattività/impulsività marcata.',
    profileAsdMasked:   'AQ-10 basso ma RAADS-14 o CAT-Q elevati: possibile camouflaging che abbassa il punteggio AQ-10. Considera una valutazione approfondita.',
    profileRaadsOnly:   'AQ-10 nella norma ma RAADS-14 sopra soglia: possibile camouflaging nei questionari o tratti autistici che emergono su scale più ampie.',
    profileAdhdOnly:    'Punteggio ASRS elevato senza tratti autistici evidenti. Il profilo è coerente con ADHD adulto.',
    profileImpuls:      'ASRS nella norma, ma il CPT mostra falsi allarmi frequenti — possibile impulsività subclinica.',
    profileInattn:      'Hit rate CPT bassa — possibile difficoltà di attenzione sostenuta, anche senza soglia ADHD nel questionario.',
    profileNorm:        'I punteggi complessivi non raggiungono le soglie cliniche. Se hai preoccupazioni, un professionista può offrire una valutazione più approfondita.',
    cptFAHigh:          '⚠️ Falsi allarmi elevati: indicatore di impulsività. ',
    cptHitLow:          '⚠️ Hit rate bassa: difficoltà di attenzione sostenuta. ',
    cptDprimeLow:       '⚠️ d\' basso: scarsa discriminazione segnale/rumore. ',
    cptNorm:            '✓ Prestazione nella norma.',
    socialEyePct:       (pct, n) => `Prime fissazioni verso gli occhi: <strong>${pct}%</strong> (${n} facce).`,
    socialHigh:         '✓ Pattern di fissazione tipico.',
    socialMid:          'Pattern borderline — alcune prime fissazioni non verso gli occhi.',
    socialLow:          '⚠️ Meno del 40% di prime fissazioni verso gli occhi — possibile atipicità nell\'attenzione sociale (proxy semplificato).',
    blinkNorm:          (bpm, n, dur) => `Blink rate: <strong>${bpm} blink/min</strong> (${n} blink in ${dur}s). Norma adulti: 12–20/min.`,
    blinkLow:           '⚠️ Blink rate molto bassa — possibile concentrazione intensa o ipocinesia.',
    blinkHigh:          '⚠️ Blink rate elevata — possibile stress o affaticamento oculare.',
    blinkOk:            '✓ Nella norma.',
    disclaimerResult:   '<strong>⚠️ Questo non è un test clinico.</strong> AQ-10: sensibilità ~79%, specificità ~84% (Baron-Cohen 2001/2012). ASRS Parte A: 68.7% sens., 99.5% spec. (Kessler 2005). RAADS-14: ~91% sens., ~84% spec. (Eriksson 2013). CAT-Q: riferimento normativo, non diagnostico (Hull et al. 2019). Rivolgiti a un neuropsichiatra o psicologo per una valutazione completa.',
    maskingNote:        '⚠️ Nota: il camouflaging/masking può ridurre i punteggi AQ-10 nelle persone autistiche, specialmente nelle donne (Hull et al. 2017).',
    refsTitle:          '📚 Riferimenti scientifici',
  },

  en: {
    // Nav steps
    stepWelcome: '1 · Welcome', stepAq10: '2 · AQ-10', stepAsrs: '3 · ASRS',
    stepRaads:   '4 · RAADS-14', stepCatq: '5 · CAT-Q',
    stepTasks:   '6 · Tasks',    stepWebcam: '7 · Webcam', stepResults: '8 · Results',
    // Welcome screen
    badgeWelcome:      'Neurodevelopmental screening',
    appSubtitle:       'Non-clinical screening for autistic traits and ADHD in adults',
    disclaimerText:    '<strong>⚠️ Important:</strong> This tool is <em>not a diagnostic test</em>. Results are indicative and do not replace evaluation by a specialist. No data is sent to remote servers — everything stays in your browser.',
    ossNotice:         '<strong>Open source · No ads · Your data stays in your browser</strong><br>Most online tests have inaccuracies and then charge €20–80 for a report. NeuroScreen uses the same scientifically validated tools, completely free, with no data collection.',
    selectTests:       'Customise your screening:',
    durationLabel:     (min) => `Estimated duration: <strong>~${min} min</strong>`,
    aq10Meta:          '10 questions · ~3 min · ASD',
    asrsMeta:          '6 questions · ~2 min · ADHD',
    raadsMeta:         '14 questions · ~5 min · ASD',
    catqMeta:          '25 questions · ~7 min · optional',
    cptMeta:           '60 seconds · objective test',
    socialMeta:        '6 trials · ~3 min',
    webcamMeta:        '45 seconds · requires HTTP',
    aq10Short:         'Short Autism Spectrum Quotient. Threshold ≥6/10. Specificity ~84% (Baron-Cohen 2012).',
    asrsShort:         'WHO-validated ADHD self-report. Threshold ≥4/6. Specificity 99.5% (Kessler 2005).',
    raadsShort:        'Detailed autism scale. 4 cognitive domains. Sens. ~91%, spec. ~84% (Eriksson 2013).',
    catqShort:         'Measures autistic camouflaging. Key for women and late-diagnosed individuals (Hull 2019).',
    cptShort:          'Objective test of sustained attention and impulsivity (Rosvold 1956; Conners 2004).',
    socialShort:       'Where do you look first? "First saccade" paradigm with SVG faces (Klin 2002).',
    webcamShort:       '2-phase test (45 s): blink rate during reading + gaze stability on a 3D shape. Requires HTTP.',
    socialTestName:    'Social Attention',
    webcamTestName:    'Eye Tracking',
    screeningIncludes: 'This screening includes:',
    aq10Desc:          '🧩 <strong>AQ-10</strong> — Autism Spectrum Quotient short form (Baron-Cohen 2001/2012)',
    asrsDesc:          '⚡ <strong>ASRS-v1.1 Part A</strong> — WHO-validated ADHD self-report (Kessler et al. 2005)',
    raadsDesc:         '🔍 <strong>RAADS-14</strong> — Ritvo Autism Asperger Diagnostic Scale, validated short form (Eriksson 2013)',
    catqDesc:          '🎭 <strong>CAT-Q</strong> — Camouflaging Autistic Traits Questionnaire (Hull et al. 2019, optional)',
    cptDesc:           '🎯 <strong>CPT Task</strong> — Continuous Performance Test, measures attention and impulsivity',
    eyeDesc:           '👁️ <strong>Eye Tracking</strong> — Blink rate analysis via webcam using MediaPipe (optional)',
    duration:          'Estimated duration: <strong>15–25 minutes</strong>',
    startBtn:          'Start screening →',
    // AQ-10
    badgeAq10:  'AQ-10 · Autism Spectrum Quotient',
    questionOf: (n, tot) => `Question ${n} of ${tot}`,
    prevBtn:    '← Back',
    nextBtn:    'Next →',
    finishBtn:  'Finish →',
    // ASRS
    badgeAsrs: 'ASRS-v1.1 Part A · ADHD',
    // RAADS-14
    badgeRaads:   'RAADS-14 · Ritvo Autism Scale',
    raadsInstr:   'For each statement, choose <strong>when it has been true for you</strong>. There are no right or wrong answers.',
    raadsNote:    'Based on the RAADS-R (Ritvo et al. 2011). Measures autistic traits across 4 domains: Language, Social Relatedness, Sensory-Motor, Circumscribed Interests. Clinical threshold: ≥14/42 (Eriksson 2013).',
    // CAT-Q
    badgeCatq:    'CAT-Q · Camouflaging Autistic Traits',
    catqInstr:    'Indicate how much you agree with each statement on a scale from <strong>1</strong> (strongly disagree) to <strong>7</strong> (strongly agree).',
    catqNote:     'The CAT-Q measures camouflaging — strategies used to hide or compensate for autistic traits in social interactions (Hull et al. 2019). Total score ≥100/175 indicates significant camouflaging.',
    catqSkipBtn:  'Skip this test →',
    catqAgree:    'Strongly agree',
    catqDisagree: 'Strongly disagree',
    // Restore banner
    restoreBannerText: 'Previous session found — would you like to restore your data?',
    restoreDate:       (d) => `Saved on ${d}`,
    restoreYes:        'Restore',
    restoreNo:         'Dismiss',
    // CPT
    badgeCpt:      'Task · CPT',
    cptTitle:      'Continuous Performance Test',
    cptInstr:      'Letters will appear in rapid succession. Press <span class="cpt-key-hint">SPACE</span> (or the button) <strong>only when you see the letter X</strong>. For all other letters, do nothing.',
    cptNote:       'The test lasts 60 seconds. It measures sustained attention and impulsivity — markers relevant to ADHD (Conners 2004; Rosvold et al. 1956).',
    cptReady:      'Ready? Click "Start" to begin.',
    cptStart:      'Start test →',
    cptTap:        'TAP / SPACE',
    cptCorrect:    'Correct',
    cptFA:         'False alarms',
    cptPressSpace: '← Press SPACE!',
    cptDontPress:  'Do not press...',
    cptDone:       'Test completed!',
    cptBadgeDone:  'CPT · Completed ✓',
    cptResultTitle:'CPT Results',
    cptHitRate:    'Hit rate',
    cptFalseAlarms:'False alarms',
    cptRtMedio:    'Mean RT',
    cptSaved:      'Data saved for the final report.',
    // Social attention
    badgeSocial:      'Task · Social Attention',
    socialTitle:      'Where do you look first?',
    socialInstr:      'A face will be shown briefly. Then indicate <strong>where you looked first</strong>.',
    socialNote:       'Based on the "first saccade" paradigm — Klin et al. (2002) documented differences in attention to the eye region between autistic and non-autistic individuals.',
    trialOf:          (n, tot) => `Trial ${n} / ${tot}`,
    readLabel:        '📖 Read the text below:',
    readHint:         'The face will appear automatically shortly — continue reading normally.',
    faceOf:           (n, tot) => `Face ${n} of ${tot}`,
    whereFirst:       'Where did you look first?',
    regionEyes:       '👀 Eyes',
    regionNose:       '👃 Nose',
    regionMouth:      '👄 Mouth',
    regionOther:      '🔲 Other',
    regionElsewhere:  '↩ I was looking elsewhere',
    socialDoneText:   (pct, seen, sk) => `Completed! ${pct}% of first fixations were toward the eyes (out of ${seen} faces seen${sk > 0 ? `, ${sk} skipped` : ''}).`,
    socialSaved:      'Data saved for the final report.',
    continueWebcam:   'Continue → Eye Tracking (optional)',
    goToResults:      'Continue → Results',
    // Webcam
    badgeWebcam:   'Eye Tracking · MediaPipe FaceMesh',
    webcamTitle:   'Blink Rate & Gaze Analysis via Webcam',
    webcamDesc:    'The webcam detects facial landmarks using <strong>MediaPipe FaceMesh</strong> (468 points, including irises). Measures:',
    webcamBlink:   '<strong>Blink rate</strong> — blinking frequency (normal: 12–20/min). Atypical values documented in some neurodivergent conditions.',
    webcamEAR:     '<strong>Eye Aspect Ratio (EAR)</strong> — eye opening index (Soukupová & Čech 2016).',
    webcamGaze:    '<strong>Gaze stability</strong> — iris position variance during fixation.',
    webcamNoHTTP:  '<strong>Webcam unavailable on file://</strong><br>Browsers block webcam access without a local server. Run <code>start.ps1</code> in the project folder, then reopen <code>http://localhost:8080</code>.<br><br>You can skip and view questionnaire results.',
    webcamStart:       'Start test →',
    webcamStartTest:   'Start test →',
    webcamPreviewBtn:  'Test webcam',
    webcamPreviewTitle:'Webcam preview — is the image sharp and your face well lit?',
    webcamPreviewHint: 'If the image is clear and your face is visible, you are ready to start.',
    webcamPrivacy:     'The webcam is never recorded — all processing happens locally in your browser. No data is transmitted.',
    webcamSetupTitle:  'Before you start:',
    webcamSetupClean:  '🧹 Clean the webcam (or front camera) with a soft cloth',
    webcamSetupLight:  '💡 Sit in front of a clear light source — avoid backlighting',
    webcamSetupDist:   '📱 Hold the device about 50 cm from your face, steady',
    webcamPhasesTitle: 'The test has two phases:',
    webcamPhase1Desc:  '📖 <strong>Phase 1 — 30 s</strong> — Read a text about mycelium; natural blink rate is measured',
    webcamPhase2Desc:  '🔺 <strong>Phase 2 — 15 s</strong> — Fixate on the centre of a rotating 3D shape; gaze stability is measured',
    webcamReadLabel:   'Phase 1 — Read normally:',
    webcamShapeLabel:  'Phase 2 — Fixate on the centre of the shape:',
    webcamSkip:        'Skip → Go to results',
    webcamLoading:     'Loading model...',
    webcamInit:        'Initialising model...',
    webcamNoFace:      'No face detected',
    webcamActive:      (s) => `Detection active — ${s}s`,
    webcamActiveRead:    (s) => `Phase 1 / 2 — Reading active — ${s}s remaining`,
    webcamActivePursuit: (s) => `Phase 2 / 2 — Fixation active — ${s}s remaining`,
    webcamDone:        'Completed ✓',
    webcamResults:     'View final results →',
    blinkTotal:        'Total blinks',
    blinkPerMin:       'Blinks/min',
    earMean:           'Mean EAR',
    gazeStability:     'Gaze detections',
    gazeStabLabel:     'Gaze stability (Phase 2)',
    gazeStab_ok:       'Stable',
    gazeStab_mod:      'Moderate',
    gazeStab_low:      'Unstable',
    // Results
    badgeResults:       'Results',
    resultsTitle:       'Neurodevelopmental Screening Report',
    aq10BlockName:      'AQ-10 · Autism',
    asrsBlockName:      'ASRS-v1.1 · ADHD',
    raads14BlockName:   'RAADS-14 · ASD Scale',
    catqBlockName:      'CAT-Q · Camouflage',
    chipLow:            'Low',
    chipMid:            'Borderline',
    chipHigh:           'High',
    faChipNone:         'None',
    faChipMod:          'Moderate',
    faChipFreq:         'Frequent',
    cptResultBlock:     '🎯 CPT Task',
    socialResultBlock:  '👁️ Social Attention',
    webcamResultBlock:  '📹 Webcam Eye Tracking',
    profileBlock:       '📊 Combined profile',
    printBtn:           '🖨️ Print report',
    restartBtn:         '↺ Restart',
    aq10Section:        '🧩 AQ-10:',
    asrsSection:        '⚡ ASRS:',
    raads14Section:     '🔍 RAADS-14:',
    catqSection:        '🎭 CAT-Q:',
    aq10Low:            'Scores do not suggest significant autistic traits (clinical threshold: 6/10).',
    aq10Mid:            'Some traits present, but below the clinical threshold. Consider how these manifest in your daily life.',
    aq10High:           (s) => `Score ${s}/10 — above the clinical threshold (≥6). It may be worth discussing this with a specialist.`,
    asrsLow:            'Scores do not suggest significant ADHD (clinical threshold: 4/6).',
    asrsMid:            'Borderline score. A full ASRS-v1.1 (18-item) assessment would provide more clarity.',
    asrsHigh:           (s) => `Score ${s}/6 — above the clinical threshold (≥4). High specificity for predicting ADHD in adults (Kessler 2005).`,
    raads14Low:         'Score below the clinical threshold (≥14/42). Does not suggest significant autistic traits on this scale.',
    raads14Mid:         (s) => `Score ${s}/42 — above the clinical threshold (≥14). Relevant autistic traits in at least one domain. Consistent with adult ASD (Eriksson 2013).`,
    raads14High:        (s) => `Score ${s}/42 — well above threshold. Marked autistic traits across multiple domains. High likelihood of ASD (Eriksson 2013).`,
    raads14Domains:     'Domains: Language · Social Relatedness · Sensory-Motor · Circumscribed Interests',
    catqLow:            (s) => `Score ${s}/175 — below threshold (≥100). Limited camouflaging reported.`,
    catqHigh:           (s) => `Score ${s}/175 — above threshold (≥100). Significant camouflaging. AQ-10/RAADS-14 scores may underestimate true autistic traits (Hull et al. 2019).`,
    catqSubscales:      (ma, as, co) => `Masking: ${ma}/63 · Assimilation: ${as}/63 · Compensation: ${co}/49`,
    profileBoth:        'High scores for both ASD and ADHD. Co-occurrence (AuDHD) is documented in 50–70% of cases (Antshel et al. 2013). A neuropsychological evaluation can distinguish the profile.',
    profileAsdOnly:     'Elevated AQ-10/RAADS-14 without strong ADHD signals. The profile is consistent with autistic traits without marked hyperactivity/impulsivity.',
    profileAsdMasked:   'Low AQ-10 but elevated RAADS-14 or CAT-Q: possible camouflaging lowering the AQ-10 score. Consider a thorough evaluation.',
    profileRaadsOnly:   'AQ-10 within normal range but RAADS-14 above threshold: possible camouflaging on questionnaires, or autistic traits emerging on broader scales.',
    profileAdhdOnly:    'High ASRS score without evident autistic traits. The profile is consistent with adult ADHD.',
    profileImpuls:      'ASRS within normal range, but CPT shows frequent false alarms — possible subclinical impulsivity.',
    profileInattn:      'Low CPT hit rate — possible sustained attention difficulties, without reaching the ADHD questionnaire threshold.',
    profileNorm:        'Overall scores do not reach clinical thresholds. If you have concerns, a professional can offer a more thorough evaluation.',
    cptFAHigh:          '⚠️ High false alarms: indicator of impulsivity. ',
    cptHitLow:          '⚠️ Low hit rate: sustained attention difficulties. ',
    cptDprimeLow:       '⚠️ Low d\': poor signal/noise discrimination. ',
    cptNorm:            '✓ Performance within normal range.',
    socialEyePct:       (pct, n) => `First fixations toward eyes: <strong>${pct}%</strong> (${n} faces).`,
    socialHigh:         '✓ Typical fixation pattern.',
    socialMid:          'Borderline pattern — some first fixations not toward the eyes.',
    socialLow:          '⚠️ Less than 40% of first fixations toward the eyes — may indicate atypicality in social attention (simplified proxy).',
    blinkNorm:          (bpm, n, dur) => `Blink rate: <strong>${bpm} blinks/min</strong> (${n} blinks in ${dur}s). Adult norm: 12–20/min.`,
    blinkLow:           '⚠️ Very low blink rate — possible intense concentration or hypokinesia.',
    blinkHigh:          '⚠️ Elevated blink rate — possible stress or eye fatigue.',
    blinkOk:            '✓ Within normal range.',
    disclaimerResult:   '<strong>⚠️ This is not a clinical test.</strong> AQ-10: ~79% sensitivity, ~84% specificity (Baron-Cohen 2001/2012). ASRS Part A: 68.7% sens., 99.5% spec. (Kessler 2005). RAADS-14: ~91% sens., ~84% spec. (Eriksson 2013). CAT-Q: normative reference, not diagnostic (Hull et al. 2019). Please consult a neuropsychiatrist or psychologist for a full evaluation.',
    maskingNote:        '⚠️ Note: camouflaging/masking can lower AQ-10 scores in autistic individuals, especially women (Hull et al. 2017).',
    refsTitle:          '📚 Scientific References',
  },
};
